(function(g){var window=this;var f3=function(a){var b={format:a.o,languageCode:a.l,languageName:a.B,displayName:g.DH(a),kind:a.A,name:a.C,id:a.Ea,is_servable:a.K,is_default:a.isDefault,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},g3=function(a){return a.g?a.g.languageCode:a.l},Qxa=function(a,b){var c=new g.CH;
c.l=a.l;c.B=a.B;c.C=a.C;c.A=a.A;c.isDefault=!1;c.F=a.F;c.D=a.D;c.H=a.H;c.g=b;return c},h3=function(a){if(!Rxa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Sxa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},i3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.fQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.B=f;this.l=k},j3=function(a,b,c,d,e){g.fQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},l3=function(a){a=void 0===a?{}:a;
var b="_"+k3++;return new j3(0,0x8000000000000,0,b,a)},m3=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.fb);a.params.fb&&g.Ga(l,a.params.fb);g.Ga(l,c.fb);k.fb=l;g.W.call(this,{G:"div",L:"caption-window",P:{id:"caption-window-"+a.id,dir:1==k.Ck?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},N:[{G:"span",L:"captions-text"}]});this.B=[];this.K=!1;this.F=a;this.D=[];this.H=[];this.Ca=e;this.ya=f;this.C=null;this.Z=.96*e;this.ia=.96*f;this.o=k;this.sa=c;this.A=this.g["captions-text"];this.na=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.M=d/360*16;this.type=0;this.ea=this.M*Txa(l);a=new g.GF(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.tO,this);a.subscribe("dragmove",this.sO,this);a.subscribe("dragend",this.rO,this);this.ga=this.fa=0;a="";this.o.Mk&&(a=h3(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.Mk+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":Uxa[this.o.textAlign]};this.na&&(b["border-radius"]=a?this.ea/
8+"px":"");g.nh(this.element,b);switch(this.o.Hf){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},Txa=function(a){var b=1+.25*(a.rj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},n3=function(a,b){var c={},d=b.background?b.background:a.o.fb.background;
if(null!=b.df||b.background){var e=null!=b.df?b.df:a.o.fb.df;d=h3(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.na&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ea/8+"px")}if(null!=b.rj||null!=b.offset)c["font-size"]=a.M*Txa(b)+"px";d=1;e=b.color||a.o.fb.color;if(b.color||null!=b.Kh)e=h3(e),d=null==b.Kh?a.o.fb.Kh:b.Kh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Yh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";
b.Ox&&(k=e=b.Ox);var l=a.M/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.sE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.fb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.pf&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.Gs&&(c.visibility="hidden");return c},Vxa=function(a,b,c){a.K=a.K||!!c;
var d={};g.Ga(d,a.o.fb);g.Ga(d,c||b.l);g.Ga(d,a.sa.fb);c=a.D[0];if(c&&d.background==c.background&&d.df==c.df&&!!d.Gs==!!c.Gs&&d.Yh==c.Yh){var e;for(e=0;e<a.D.length;e++)if(g.$b(d,a.D[e])){var f=a.H[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Dd("SPAN");g.nh(f,n3(a,e));a.H[0].appendChild(f);e=1}a.H.length=e;a.D.length=e}else a.H.length=0,a.D.length=0,f=g.Dd("SPAN"),g.nh(f,n3(a,d)),a.A.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Jd(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.B.length||!b.B){if(0<e||0!=a.B.length){var m=g.Dd("BR");f.appendChild(m)}f.appendChild(g.Ed("\u00a0"));a.C=g.Ed("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.Ed(l):l,m))}a.D.push(d);a.H.push(f);a.B.push(b)},Wxa=function(){},p3=function(){this.A=this.l=this.mode=this.o=0;
this.B=new o3(this);this.C=new o3(this);this.g=[];this.clear()},Yxa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{wn:a,
xn:b,result:0};a=Xxa[a];b=Xxa[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{wn:a,xn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{wn:a,xn:b,result:2};return{wn:a,xn:b,result:3}},$xa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,Zxa(a.B,b,c,d))},aya=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?$xa(a,d.Jx,d.Kx,b):1==d.type&&a.o&496&&Zxa(a.C,d.Jx,d.Kx,b)}a.g.length=0},q3=function(){this.g=0},r3=function(){this.l=this.o=this.g=0},s3=function(){this.timestamp=this.ue=0},t3=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new s3}this.g=this.l=this.row=0;this.style=new q3;this.B=a;this.A=0},u3=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.o[m][q];
if(0!=r.ue){0==c&&(c=m,d=q);n=String.fromCharCode(r.ue);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.ue||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],r=q.ue,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},fya=function(a,b){switch(a){case 0:return bya[(b&127)-32];
case 1:return cya[b&15];case 2:return dya[b&31];case 3:return eya[b&31]}return 0},v3=function(a){return a.o[a.row][a.l]},w3=function(a,b,c){2<=b&&1<a.l&&(--a.l,v3(a).ue=0);
var d=v3(a);d.timestamp=a.B.l+0;d.ue=fya(b,c);32>a.l&&a.l++},gya=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].Mn(a.o[c+e][f])},x3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},y3=function(a){a.row=0<a.g?a.g:1;
a.l=1;x3(a,0,15)},z3=function(a){this.A=a;
this.B=0;this.style=new q3;this.C=new t3(a);this.D=new t3(a);this.F=new t3(a);this.l=this.C;this.o=this.D;this.g=this.l},A3=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:u3(d,c),y3(a.l),y3(a.o),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(u3(d,c),x3(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},hya=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},iya=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},o3=function(a){this.l=a;
this.g=new r3;this.B=0;this.o=new z3(a);this.C=new z3(a);this.A=this.o},Zxa=function(a,b,c,d){a.g.update();
b=Yxa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.wn;c=b.xn;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&w3(a,0,b),c&96&&w3(a,0,c),0!=b&&0!=c&&3==a.style.g&&u3(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;gya(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));x3(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:w3(b.g,0,32);break a;case 48:57==c?(b=b.g,v3(b).ue=0,32>b.l&&b.l++):w3(b.g,1,c&15)}break;case 2:c&32&&w3(b.g,2,c&31);break;case 3:c&32&&w3(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:hya(b);break;
case 33:b=b.g;1<b.l&&(--b.l,v3(b).ue=0);break;case 36:b=b.g;d=v3(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:A3(b,2,d);break;case 38:A3(b,3,d);break;case 39:A3(b,4,d);break;case 40:w3(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);y3(d);iya(b);break;case 43:iya(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:u3(a,d)}x3(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;u3(a,d);gya(a,b,b+1,a.g-1);x3(a,a.row,1)}break;case 46:x3(b.o,0,15);break;case 47:u3(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;hya(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},B3=function(){},C3=function(a){this.l=a;
this.g=null},kya=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Rr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");jya(d,e,k,b,f,a.firstChild,{},c)},jya=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.pf=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");D3.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new i3(a,b,c,d,n.nodeValue,e||0<m,g.Wb(k)?void 0:k));else{var q={};g.Ga(q,k);jya(a,b,c,d,e||0<m,n,q,l)}}},E3=function(){this.l={};
this.g=null},F3=function(a){this.A={};
this.H={};this.I={};this.B="_"+k3++;this.C=a;this.F={};this.l=this.g=null;this.D=!0},G3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},H3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},I3=function(a,b){var c=G3(a,b);
if(void 0!=c)return c},J3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return D3.test(c),c},lya=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.I[d]:a.C);d=I3(b,"mh");null!=d&&(c.Ot=d);d=I3(b,"ju");null!=d&&(c.textAlign=d);d=I3(b,"pd");null!=d&&(c.Ck=d);d=J3(b,"wfc");null!=d&&(c.windowColor=d);d=G3(b,"wfo");void 0!=d&&(c.Mk=d/255);return c},mya=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.H[d]);d=I3(b,"ap");null!=d&&(c.Hf=d);d=G3(b,"cc");null!=d&&(c.Cr=d);d=G3(b,"ah");null!=d&&(c.Pe=d);d=G3(b,"rc");null!=d&&(c.Rp=d);d=G3(b,"av");null!=d&&(c.kg=d);return c},nya=function(a,b,c,d){var e={};
g.Ga(e,mya(a,b));g.Ga(e,lya(a,b));d?g.$b(e,a.C)?(d=a.B,e=a.C):d="_"+k3++:d=b.getAttribute("id")||"_"+k3++;a=G3(b,"t")+c;b=G3(b,"d")||0x8000000000000;return new j3(a,b,0,d,e)},K3=function(a,b,c){this.D=c;
this.version=this.C=this.A=this.g=0;this.l=new window.DataView(a);this.o=[]},L3=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},M3=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},N3=function(a,b){this.l=a;
this.track="CC3"==b.B?4:0;this.g=new p3;this.g.o=1<<this.track},pya=function(a){if(g.u(a))return!1;
a=new K3(a,8,0);return oya(a)},oya=function(a){if(!(a.g<a.l.byteLength)||1380139777!=M3(a))return!1;
a.version=L3(a);if(1<a.version)return!1;L3(a);L3(a);L3(a);return!0},qya=function(){this.l=[];
this.g=[]},O3=function(a,b){return b?a.g.concat(a.l):a.g},P3=function(a,b){switch(b.A){case "asr":var c=a.l;
g.La(c,(0,g.z)(b.I,b))||c.push(b);break;default:c=a.g,g.La(c,(0,g.z)(b.I,b))||c.push(b)}},Q3=function(){},rya=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.pf=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new i3(b,c,d,e.id,q.nodeValue,f||0<n,g.Wb(l)?void 0:l),m.push(q),e.l.push(q);else{var r={};g.Ga(r,l);rya(a,b,c,d,e,!0,q,r,m)}}},R3=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},sya=function(a,b,c,d){d=Object.assign({Ot:0},d);
return new j3(a,b,c,"_"+k3++,d)},S3=function(a){g.M.call(this);
this.Wz=!!a;this.l=new qya;this.D=[];this.g=null},uya=function(a){var b={};
if(a=g3(a))b.lang=a,tya.test(a)&&(b.Ck=1);return b},vya=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.u(b)){var f=new window.DataView(b);1718909296==f.getUint32(4)&&(f=g.nJ(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),pya(b)||(b=g.de(new window.Uint8Array(b))))}if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new Q3),a.g.o(b,d);b=g.Rr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new F3(uya(c)):a.g=new E3:a.g=new C3(uya(c)));return a.g.o(b,d)}try{if(pya(b))return a.g||(a.g=
new N3(e,c)),a.g.o(b,d)}catch(k){g.OD(k)}return[]},T3=function(a){S3.call(this,a.Dn);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},U3=function(){this.qb=[]},V3=function(a,b,c,d,e,f){g.M.call(this);
this.J=a;this.A=b;this.C=new U3;this.g=null;this.H=d;this.K=f;this.o=this.l=null;this.F=c;this.D=e||!1;this.I=new g.Ut(this.qA,1E3,this);g.N(this,this.I);this.B=new g.BF(this);g.N(this,this.B);this.B.O(b,"seekto",this.sB);this.sB(b.getCurrentTime());this.qA()},wya=function(a,b){var c=a.g;
a.g=g.Ja(a.F.yg(b).g);c!=a.g&&a.K&&a.K()},xya=function(a,b){var c=g.HK(b,a.J,{}).Sa(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.o=g.HE(c,d,3,100).then((0,g.z)(a.gT,a));a.l=b;c=a.C;d=a.l.g[0].wa;var e=g.eb(c.qb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.qb[e-1]&&e<c.qb.length&&1==c.qb[e]-d?(g.Ta(c.qb,e),g.Ta(c.qb,e-1)):0<e&&1==d-c.qb[e-1]?c.qb[e-1]=d:e<c.qb.length&&1==c.qb[e]-d?c.qb[e]=d:(g.$a(c.qb,e,0,d),g.$a(c.qb,e+1,0,d)))},W3=function(a,b){S3.call(this);
this.o=a;this.A=b;this.B=null;this.C=!1},yya=function(a,b){if(b in a.o.g)return a.o.g[b];
if(g.iL(a.o))for(var c in a.o.g){var d=a.o.g[c];if(g.UH(d.info.mimeType)&&("386"!=c||g.Y(a.A).experiments.g("html5_manifestless_captions_fmt3")))return d}return null},X3=function(a,b){return a.Aa&&null!=a.oa||g.Y(b).Pa&&null!=a.oa&&null!=a.oa.g.rawcc},Y3=function(a,b,c,d,e,f){m3.call(this,a,b,c,d,e,f);
this.type=1},Z3=function(a,b,c,d,e,f){m3.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.J=this.R=0;this.X=this.I=window.NaN;this.ra=null;this.ba=new g.Ut(this.kT,433,this);g.N(this,this.ba)},$3=function(a){if(!a.R){var b=g.Dd("SPAN");
g.nh(b,n3(a,a.o.fb));a.A.appendChild(b);b.appendChild(g.Ed("M"));var c=b.offsetHeight,d=g.Dd("BR");b.appendChild(d);b.appendChild(g.Ed("M"));a.R=b.offsetHeight-c;a.A.removeChild(b)}return a.R},zya=function(a){if((0,window.isNaN)(a.I)){var b=a.o.Cr;
if(b){var c=g.Dd("SPAN");g.Rd(c,"\u2013".repeat(b));g.nh(c,n3(a,a.o.fb));a.A.appendChild(c);a.I=c.offsetWidth;a.A.removeChild(c)}else a.I=0}return a.I},a4=function(a,b,c,d){S3.call(this,d);
c=c||g.$D(a).hl||"";c=c.split("_").join("-");this.B=g.bE(a,{hl:c});this.A=b;this.C={};this.o=null},d4=function(a){g.yV.call(this,a);
this.A=g.Y(a);this.o=a.getVideoData();this.na=g.cV(a);this.I=a;var b=null,c=g.kD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.UC(c));this.Z=b;this.C={fb:{}};this.F={fb:{}};this.M=[];this.R={};this.Y={};this.K=!1;this.ra="1"==this.o.jc.cc_auto_caps||"1"==this.A.Vb.cc_auto_caps;b="3"==this.A.A&&!!a.app.B&&a.app.B.Hm();this.D=(c=!this.A.experiments.g("web_player_native_controls_live_captions_fix_killswitch"))?b&&!this.o.Aa:b;this.ga=c&&b&&this.o.Aa&&X3(this.o,this.I);c=b=this.l=this.B=
this.H=this.J=this.X=this.ia=null;this.D||(b=new g.Rt(this.QE,void 0,this),g.N(this,b),c=new g.Ut(this.VU,2E3,this),g.N(this,c));this.ba=b;this.fa=c;this.W=new g.BF(this);g.N(this,this.W);this.D||this.W.O(a,"resize",this.Iv);this.W.O(a,"onPlaybackAudioChange",this.iQ);this.W.O(a,"crn_captions",this.wM,this);this.W.O(a,"crx_captions",this.xM,this);b4(this,c4(this,"display-settings")||{})},Aya=function(a){if(1==a.A.Zg||1==a.o.Zg||"alwayson"==g.CO(a.o,"yt:cc"))return!0;
if(2==a.A.Zg){var b=c4(a,"module-enabled");if(null!=b)return!!b}if(a.o.captionTracks.length)var c=a.g.getAudioTrack().vr;return"ON"==c||"on"==g.CO(a.o,"yt:cc")},e4=function(a,b){if(a.l&&(void 0===b||!b)||!a.o.captionTracks.length)return!1;
var c=a.g.getAudioTrack();return!!c.co||"FORCED_ON"==c.vr},g4=function(a,b){if(a.B){var c=O3(a.B.l,b||a.ra);
if(a.H&&a.H.g)return a.H.g;for(var d=[a.o.Yg,a.A.Yg,g.CO(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(g3(c[f])==d[e])return c[f];return a.H&&a.H.Nr?a.H.Nr:(d=c.find(function(a){return a.isDefault}))?d:c[0]||f4(a)}return null},f4=function(a){return a.H&&a.H.co},Bya=function(a,b){for(var c=a.I.app.B.la().textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},i4=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&h4(a,"module-enabled",!!b));a.l=b;e4(a)&&(a.l=f4(a));a.load(d)},Cya=function(a){if(a.l!=f4(a)){if(a.K&&!g.FM(a.A)&&!g.MM(a.A)){g.Xt(a.fa);
var b=l3({Hf:0,Pe:5,kg:5,Rp:2,textAlign:0,Ck:0,lang:"en-GB"});a.X=[b];var c=["Click "," for settings"];if(!a.ia){var d=new g.gH(g.Ioa());g.N(a,d);a.ia=d.element}d=b.end-b.start;var e=g.DH(a.l);e&&a.X.push(new i3(b.start,d,0,b.id,e));a.X.push(new i3(b.start,d,0,b.id,c[0]),new i3(b.start,d,0,b.id,a.ia,!0),new i3(b.start,d,0,b.id,c[1],!0));g.oV(a.g,a.X);g.Vt(a.fa)}if(a.K||g.FM(a.A))h4(a,"module-enabled",!0),a.H&&(a.H.g=a.l);(a=g.aV(a.g.app))&&a.C&&g.VO(a.C.o)}},Dya=function(a,b){var c=g.fZ(a.na,!0).height;
if(!c)return null;var d=a.na.Na();switch(null!=b.params.Ot?b.params.Ot:b.params.GV?2:1<b.l.length?1:0){case 1:return new Y3(b,a.C,a.F,c,d.width,d.height);case 2:return new Z3(b,a.C,a.F,c,d.width,d.height);default:return new m3(b,a.C,a.F,c,d.width,d.height)}},b4=function(a,b,c){var d=j4.fb;
a.C={};g.Ga(a.C,j4);a.C.fb={};g.Ga(a.C.fb,d);a.F={fb:{}};var e=b.backgroundOverride?a.F:a.C,f=b.background||d.background;D3.test(f);e.fb.background=f;e=b.colorOverride?a.F:a.C;f=b.color||d.color;D3.test(f);e.fb.color=f;e=b.windowColorOverride?a.F:a.C;f=b.windowColor||j4.windowColor;D3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.C;f=b.backgroundOpacity;null==f&&(f=d.df);e.fb.df=f;e=b.fontSizeIncrementOverride?a.F:a.C;f=b.fontSizeIncrement;null==f&&(f=d.rj);e.fb.rj=f;f=b.fontStyleOverride?
a.F:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.pf?3:d.bold?1:d.pf?2:0);f=f.fb;switch(e){case 1:f.bold=!0;delete f.pf;break;case 2:delete f.bold;f.pf=!0;break;case 3:f.bold=!0;f.pf=!0;break;default:delete f.bold,delete f.pf}e=b.textOpacityOverride?a.F:a.C;f=b.textOpacity;null==f&&(f=d.Kh);e.fb.Kh=f;e=b.windowOpacityOverride?a.F:a.C;f=b.windowOpacity;null==f&&(f=j4.Mk);e.Mk=f;e=b.charEdgeStyleOverride?a.F:a.C;f=b.charEdgeStyle;null==f&&(f=d.Yh);e.fb.Yh=f;e=b.fontFamilyOverride?a.F:a.C;f=b.fontFamily;null==
f&&(f=d.fontFamily);e.fb.fontFamily=f;a.loaded&&a.Iv();c&&h4(a,"display-settings",b)},Fya=function(a,b){if(b&&!a.J){var c=l3({Ck:0,
lang:"en-GB"});a.J=[c,new i3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.oV(a.g,a.J)}else!b&&a.J&&(Eya(a,a.J),a.J=null)},Eya=function(a,b){g.qV(a.g,b);
(0,g.B)(b,function(a){g.Ua(this.M,a)},a);
a.ba.wl()},Gya=function(a,b){return a&&g.u(a)&&D3.test(a)?a:b},Hya=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Iya=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?g.cd(a,-2,4):b},c4=function(a,b){if(!a.Z)return null;
try{var c=a.Z.get(b)}catch(d){a.Z.remove(b)}return c},h4=function(a,b,c){if(a.Z)try{a.Z.set(b,c)}catch(d){}};
g.lY.prototype.kj=g.ca(13,function(){for(var a=g.pd(window.document,"track",void 0,this.g),b=0;b<a.length;b++)g.Jd(a[b])});
g.UY.prototype.kj=g.ca(12,function(){this.g.kj()});
g.lY.prototype.Hm=g.ca(11,function(){return!!this.g.textTracks});
g.UY.prototype.Hm=g.ca(10,function(){return this.g.Hm()});
g.lY.prototype.Qk=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.UY.prototype.Qk=g.ca(8,function(a){this.g.Qk(a)});
g.VI.prototype.po=g.ca(2,function(a){return(a=this.gi(a))?a.l:0});
g.ZK.prototype.po=g.ca(1,function(){return 0});
g.CH.prototype.I=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var tya=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Sxa=/#(.)(.)(.)/,Rxa=/^#(?:[0-9a-f]{3}){1,2}$/i,D3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Uxa=["left","right","center"];var j4={windowColor:"#080808",Mk:0,textAlign:2,Hf:7,Pe:50,kg:100,fb:{background:"#080808",df:.75,Yh:0,color:"#fff",fontFamily:4,rj:0,Kh:1,offset:1}};g.p(i3,g.fQ);g.p(j3,g.fQ);var k3=0;g.p(m3,g.W);g.h=m3.prototype;g.h.tO=function(a,b){var c=g.Eh(this.element,this.element.parentElement);this.fa=a-c.x;this.ga=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.sO=function(a,b){var c=g.Hh(this.element),d=a-this.fa-.02*this.Ca,e=b-this.ga-.02*this.ya,f=(d+c.width/2)/this.Z*3;f=Math.floor(g.cd(f,0,2));var k=(e+c.height/2)/this.ia*3;k=Math.floor(g.cd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.Z;d=100*g.cd(d,0,1);c=(e+k/2*c.height)/this.ia;c=100*g.cd(c,0,1);this.F.params.Hf=l;this.F.params.kg=c;this.F.params.Pe=d;this.o.Hf=l;this.o.kg=c;this.o.Pe=d;this.HD()};
g.h.rO=function(){g.hq(this.element,"ytp-dragging")};
g.h.HD=function(){this.Ri(this.B)};
g.h.Sb=function(){return this.type};
g.h.Ri=function(a){var b=Math.min(this.Wy(),this.Z),c=this.Vy();g.nh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.lr(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.o.Pe+2,e=this.o.Hf;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.o.kg+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.nh(this.element,a)};
g.h.lr=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.K||this.B.length>b)b=0,this.K=!1,this.B=[],this.D=[],this.H=[],this.C=null,g.Hd(this.A);for(;b<a.length;b++)Vxa(this,a[b])};
g.h.Wy=function(){return 0};
g.h.Vy=function(){return 0};Wxa.prototype.B=function(){};p3.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
p3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Xxa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];q3.prototype.set=function(a){this.g=a};
q3.prototype.get=function(){return this.g};
r3.prototype.clear=function(){this.g=0};
r3.prototype.update=function(){this.g=2==this.g?1:0};
r3.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
s3.prototype.Mn=function(a){this.ue=a.ue;this.timestamp=a.timestamp};
s3.prototype.reset=function(){this.timestamp=this.ue=0};
t3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.ue?a+"_":a+String.fromCharCode(d.ue)}a+="\n"}return a};
t3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.row=1};
var bya=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],cya=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],dya=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],eya=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];z3.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
o3.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};B3.prototype.reset=function(){};g.p(C3,B3);C3.prototype.o=function(a){var b=[];this.g||(this.g=l3(this.l),b.push(this.g));a=Array.from(a.firstChild.childNodes);a=g.ma(a);for(var c=a.next();!c.done;c=a.next())kya(c.value,this.g.id,b);return b};g.p(E3,B3);
E3.prototype.o=function(a){var b=[];this.g||(this.g=l3(),this.l[this.g.id]=this.g,b.push(this.g));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.l[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=l3());
var k={};f&&(g.Ga(k,f.params),f=f.params.fb)&&(k.fb={},g.Ga(k.fb,f));e.getAttribute("rc")&&(k.Rp=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.Cr=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Hf=0>f||8<f?7:f);e.getAttribute("ah")&&(k.Pe=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.kg=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Ck=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Ck=0));e.getAttribute("bc")&&(k.fb||(k.fb={}),k.fb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.fb||(k.fb={}),k.fb.df=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.fb||(k.fb={}),k.fb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.GV=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"_"+k3++;c=new j3(c,f,0,e,k)}else c=null}this.l[d]=c;b.push(c);break;case "text":for(d=[],kya(a,this.g.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.l[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(F3,B3);F3.prototype.reset=function(){this.F={};this.l=this.g=null;this.D=!0};
F3.prototype.o=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);var c=Array.from(a.firstChild.childNodes);c=g.ma(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.ma(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Ga(l,this.A[m]);m=H3(c,"b");null!=
m&&(l.bold=m);m=H3(c,"i");null!=m&&(l.pf=m);m=H3(c,"u");null!=m&&(l.underline=m);m=I3(c,"et");null!=m&&(l.Yh=m);m=I3(c,"of");null!=m&&(l.offset=m);m=J3(c,"bc");null!=m&&(l.background=m);m=J3(c,"ec");null!=m&&(l.Ox=m);m=J3(c,"fc");null!=m&&(l.color=m);m=I3(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=G3(c,"sz");void 0!=m&&(l.rj=m/100-1);m=G3(c,"bo");void 0!=m&&(l.df=m/255);c=G3(c,"fo");void 0!=c&&(l.Kh=c/255);k[d]=l;break;case "ws":d=c.getAttribute("id");this.I[d]=lya(this,c);break;case "wp":d=c.getAttribute("id"),
this.H[d]=mya(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.ma(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=nya(this,d,e,!1);(d=this.F[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.F[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!H3(d,"a");n=(G3(d,"t")||0)+n;var q=G3(d,"d")||5E3;m||(!this.D&&this.l&&this.l.windowId==l&&this.l.end>n&&(this.l.end=n),this.l&&"\n"==this.l.text&&(this.l.text=
""));var r=m?6:5,v=this.A[d.getAttribute("p")],D=d.childNodes;D.length&&(this.D=null!=d.getAttribute("d"));for(var H=0;H<D.length;H++){var L=D[H];0<H&&(m=!0);var T=void 0;1==L.nodeType&&(T=L);if(T&&"s"==T.tagName){var ha=T;L=n;T=q;var db=l,sa=m,Sd=r,Bh=ha.textContent?ha.textContent:"",rb=this.A[ha.getAttribute("p")];ha=G3(ha,"t")||0;L=new i3(L+ha,T-ha,Sd,db,Bh,sa,rb)}else L=new i3(n,q,r,l,L.textContent||"",m,v);k.push(L);this.l=L}if(0<k.length)for(k[0].windowId==this.B&&(this.g=nya(this,d,e,!0),c.push(this.g)),
d=g.ma(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,this.g.l.push(k),c.push(k)}e=c}else e=[];return e};g.p(K3,Wxa);K3.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+k3++;c=c/1E3-this.D;d=d/1E3-this.D;a=new j3(c,d-c,5,f,{textAlign:0,Hf:0,Pe:2.5*b,kg:5.33*a});e=new i3(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.p(N3,B3);N3.prototype.o=function(a){a=new K3(a,a.byteLength,this.l);if(oya(a)){for(;a.g<a.l.byteLength;)for(0==a.version?a.A=M3(a)*(1E3/45):1==a.version&&(a.A=4294967296*M3(a)+M3(a)),a.C=L3(a);0<a.C;a.C--){var b=L3(a),c=L3(a),d=L3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.A,type:this.track,Jx:c,Kx:d,order:b.g.length}))}aya(this.g,a);return a.o}return[]};
N3.prototype.reset=function(){this.g.clear()};g.p(Q3,B3);
Q3.prototype.o=function(a,b){for(var c=[],d=a.split(Jya),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Kya.test(f)){var l=k4.exec(f);if(l&&4<=l.length){var m=R3(l[1]),n=R3(l[2])-m;m+=k;var q,r=q=void 0,v=void 0,D=void 0,H=l[3];l={textAlign:2};H=g.ma(H?H.split(" "):[]);for(var L=H.next();!L.done;L=H.next())if(L=L.value.split(":"),2==L.length){var T=L[1];switch(L[0]){case "line":L=T.split(",");L[0].endsWith("%")&&(D=L[0],l.kg=Number.parseInt(D,10),2==L.length&&(v=L[1].trim()));break;case "position":L=T.split(",");
r=L[0];l.Pe=Number.parseInt(r,10);2==L.length&&(q=L[1].trim());break;case "align":switch(T){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}D||(l.kg=100,v||(v="end"));if(!r)switch(l.textAlign){case 0:l.Pe=0;break;case 1:l.Pe=100;break;default:l.Pe=50}r=0;switch(v){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(q){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Hf=0>r||8<r?7:r;q=l;f=f.substring(k4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=sya(m,n,5,r),n=new i3(m,n,5,k.id,q,!1,g.Wb(f)?void 0:f),c.push(k),c.push(n),k.l.push(n);else for(v=q.split(Lya),1==v.length?(q=5,r=sya(m,n,q,r)):(D=q=6,r=Object.assign({Cr:32},r),r=new j3(m,n,D,"_"+k3++,r)),c.push(r),D=m,l=0;l<v.length;l++)H=v[l],0==l%2?(L=g.Rr("<html>"+H+"</html>"),L.getElementsByTagName("parsererror").length?
(T=L.createElement("span"),T.appendChild(L.createTextNode(H))):T=L.firstChild,rya(this,D,n-(D-m),q,r,0<l,T,f,c)):D=R3(H)+k}k4.lastIndex=0}}return c};
var Kya=/^NOTE/,Jya=/(?:\r\n|\r|\n){2,}/,k4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Lya=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(S3,g.M);S3.prototype.trackCount=function(){return O3(this.l,!0).length};
S3.prototype.Nd=function(){this.g=null};
S3.prototype.V=function(){g.M.prototype.V.call(this);this.Nd()};
S3.prototype.pD=function(){return!1};g.p(T3,S3);g.h=T3.prototype;g.h.It=function(a,b){var c=this.tl(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Nd();this.o=g.jE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Jt=function(a,b,c,d){this.A=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())P3(this.l,c.value);a()};
g.h.tl=function(a){var b=a.Sa(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.bE(b,c)};
g.h.Nd=function(){S3.prototype.Nd.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Nd();S3.prototype.V.call(this)};U3.prototype.contains=function(a){a=g.eb(this.qb,a);return 0<=a||0>a&&1==(-a-1)%2};
U3.prototype.length=function(){return this.qb.length/2};g.p(V3,g.M);g.h=V3.prototype;g.h.V=function(){g.M.prototype.V.call(this);this.o&&this.o.cancel()};
g.h.sB=function(a){var b=this;if(this.F.Sj())var c=this.B.O(this.A,"progresssync",function(){b.F.index.Ib()&&(b.reset(),b.g=null,wya(b,b.A.getCurrentTime()),b.B.Da(c))});
else wya(this,a)};
g.h.reset=function(){this.C=new U3;this.o&&(this.o.cancel(),this.o=null)};
g.h.qA=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Fg(a);!a||this.o||this.g&&30<this.g.startTime-this.A.getCurrentTime()||(a=this.g,a=a.g.Yj(a),!g.Y(this.A).experiments.g("disable_captions_unknown_requests")&&!a.g[0].duration)||(this.C.contains(a.g[0].wa)||xya(this,a),this.g=g.Ja(a.g));this.I.start()};
g.h.gT=function(a){var b=!(this.D?a.response:a.responseText)||400<=a.status;if(!g.Y(this.A).experiments.g("disable_captions_redirects_redux")){var c=g.dL(a);if(c){a=g.HK(this.l,this.J,{});b=this.l;g.DK(b.l,a,c);b.requestId=a.get("req_id");xya(this,this.l);return}}b||null===this.H||(this.D?this.H(a.response,1E3*this.l.g[0].startTime,this.l.g[0].wa):this.H(a.responseText,1E3*this.l.g[0].startTime,this.l.g[0].wa));this.o=this.l=null};g.p(W3,S3);g.h=W3.prototype;g.h.It=function(a,b){this.Nd();var c=yya(this,a.l);if(c){var d=c.index.po(c.index.gf());g.Y(this.A).experiments.g("html5_disable_caption_starttime")||(d-=c.index.Ld(c.index.gf()));d*=1E3;var e=g.Y(this.A).Pa;this.B=new V3(new g.mK,this.A,c,function(c,e,l){b(c,a,e,d,l)},e||g.QH(c.info),(0,g.z)(function(){this.B&&this.B.reset();
this.g&&this.g.reset();this.C=!0},this))}};
g.h.pD=function(){var a=this.C;this.C=!1;return a};
g.h.Jt=function(a){if(g.Y(this.A).Pa)P3(this.l,new g.CH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),P3(this.l,new g.CH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));else for(var b in this.o.g){var c=this.o.g[b];if(g.UH(c.info.mimeType)&&"rawcc"!=b&&("386"!=b||g.Y(this.A).experiments.g("html5_manifestless_captions_fmt3"))){var d="en",e="English",f=".en";if(c=c.info.captionTrack)d=
c.languageCode,e=c.displayName,f=c.vssId;P3(this.l,new g.CH({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f}))}}a()};
g.h.Nd=function(){S3.prototype.Nd.call(this);this.B&&(this.B.dispose(),this.B=null)};
g.h.tl=function(){return""};
g.h.V=function(){this.Nd();S3.prototype.V.call(this)};g.p(Y3,m3);Y3.prototype.lr=function(a){var b=this.F.l;m3.prototype.lr.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ga(d,c.l);g.Ga(d,Mya);var e=c.l;var f=d}Vxa(this,c,d)}};
var Mya={Gs:!0};g.p(Z3,m3);g.h=Z3.prototype;g.h.HD=function(){g.Wt(this.ba)};
g.h.kT=function(){g.hq(this.element,"ytp-rollup-mode");this.Ri(this.ra,!0)};
g.h.Wy=function(){return this.J};
g.h.Vy=function(){return this.F.params.Rp*$3(this)};
g.h.Ri=function(a,b){this.ra=a;if($3(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=this.J;this.J=0;m3.prototype.Ri.call(this,a);d=this.A.offsetWidth+1;this.J=Math.max(zya(this),c,d);c=this.F.params.Rp*$3(this)-this.A.offsetHeight;c!=this.X&&(b||(0,window.isNaN)(this.X)||(g.S(this.element,"ytp-rollup-mode"),g.Vt(this.ba)),g.nh(this.A,"transform",c?"translateY("+c+"px)":""),this.X=c);m3.prototype.Ri.call(this,a)}else m3.prototype.Ri.call(this,
a)};g.p(a4,S3);g.h=a4.prototype;g.h.It=function(a,b){var c=this.tl(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Nd();this.o=g.jE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Jt=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.Wz&&(b.asrs=1);d=g.bE(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),v=m.getAttribute("kind"),D=m.getAttribute("id"),H="true"==m.getAttribute("lang_default"),
L="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");P3(d,new g.CH({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:v,id:D,is_servable:!0,is_translateable:L,vss_id:m,is_default:H}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),v="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:q,id:r,
is_default:v},this.C[l.languageCode]=l.languageName,this.D.push(new g.BH(l))}a()},this);
this.Nd();this.o=g.jE(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.tl=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.C,kind:a.A,fmt:a.o};a.g&&(c.tlang=g3(a));return b=g.bE(b,c)};
g.h.Nd=function(){S3.prototype.Nd.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Nd();S3.prototype.V.call(this)};g.p(d4,g.yV);g.h=d4.prototype;g.h.V=function(){if(this.D){var a=this.I.app.B;a&&a.kj()}else Fya(this,!1);g.yV.prototype.V.call(this)};
g.h.QA=function(){return this.D?!this.o.Aa:this.ga||e4(this)?!0:Aya(this)};
g.h.load=function(a){g.yV.prototype.load.call(this);this.H=this.g.getAudioTrack();if(this.B||a)this.l&&(this.D&&!this.A.experiments.g("disable_native_caption_api")?Bya(this,!0):a?this.ZC(a,this.l):3!=this.g.Qa()&&this.B.It(this.l,(0,g.z)(this.ZC,this))),this.l&&this.l!=f4(this)?this.g.va("captionschanged",f3(this.l)):this.g.va("onCaptionsTrackListChanged");else{var b;X3(this.o,this.I)?b=new W3(this.o.oa,this.g):this.o.captionTracks.length?b=new T3(this.o):b=new a4(this.o.En,this.o.videoId,this.o.Yg||
this.A.Yg||g.CO(this.o,"yt:cc_default_lang")||this.A.ya,this.o.Dn);this.B=b;b.Jt((0,g.z)(this.PT,this),!0,this.D?"vtt":void 0,this.g.getAudioTrack())}};
g.h.unload=function(){this.D?this.A.experiments.g("disable_native_caption_api")?this.I.app.B.kj():this.l&&Bya(this,!1):(this.fa&&g.Xt(this.fa),g.rV(this.g,"captions"),this.M=[],this.B&&this.B.Nd(),this.J&&g.oV(this.g,this.J),this.Iv());g.yV.prototype.unload.call(this);var a=g.aV(this.g.app);a&&a.C&&g.VO(a.C.o);this.g.va("captionschanged",{})};
g.h.PT=function(){var a;this.K||Aya(this)?a=g4(this,this.K):e4(this)&&(a=f4(this));if(this.D||this.ga){for(var b=O3(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.DH(e),srclang:g3(e),id:e.toString()};this.ga||(f.src=this.B.tl(e));e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}this.I.app.B.Qk(c);(a=this.I.app.B.la())&&a.textTracks&&a.textTracks.addEventListener&&!this.A.experiments.g("disable_native_caption_api")&&this.W.O(a.textTracks,"change",this.QT)}else!this.l&&a&&
i4(this,a),this.g.va("onCaptionsTrackListChanged"),this.g.va("onApiChange")};
g.h.QT=function(){for(var a=this.I.app.B.la().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=O3(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&i4(this,b,!0)};
g.h.SV=function(){this.A.experiments.g("disable_native_caption_api")?this.loaded&&!this.D&&this.unload():!this.l&&this.D||this.unload()};
g.h.ZC=function(a,b,c,d,e){a&&(this.B.pD()&&(this.M=[],g.rV(this.I,"captions"),this.ba.wl()),a=vya(this.B,a,b,c,d),this.A.experiments.g("debug_web_player_live_captions_segment_numbers")&&c&&e&&(c=a.reduce(function(a,b){return b.start<a?b.start:a},Number.MAX_SAFE_INTEGER),b=a.reduce(function(a,b){return b.end>a?b.end:a},c)-c,d=new j3(c,b,0,"_"+k3++,{Hf:2,
Pe:100,kg:0}),a.push(d),e=new i3(c,b,0,d.id,"sq="+e),a.push(e)),g.oV(this.g,a),this.K&&!this.ga&&Cya(this),this.K=!1)};
g.h.wM=function(a){this.M.push(a);this.ba.wl()};
g.h.xM=function(a){g.Ua(this.M,a);var b=X3(this.o,this.I)&&this.A.Pa;!this.A.experiments.g("disable_remove_displayed_close_caption_cue")&&b&&g.qV(this.g,[a]);this.ba.wl()};
g.h.LU=function(a){if(a instanceof j3){var b=this.R[a.id];b&&b.F!=a&&(b.dispose(),delete this.R[a.id],b=null);b||(b=Dya(this,a))&&(this.R[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.VU=function(){Eya(this,this.X);this.X=null};
g.h.QE=function(){this.ba.stop();g.Xb(this.Y);this.M.sort(g.hQ);var a=this.M;if(this.J){var b=(0,g.Kd)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.B)(a,this.LU,this);g.Jb(this.R,function(a,b){this.Y[b]?(a.element.parentNode||g.tV(this.g,a.element,4),a.Ri(this.Y[b])):(a.dispose(),delete this.R[b])},this)};
g.h.GD=function(){b4(this,{},!0)};
g.h.ks=function(){var a=j4.fb;a={background:a.background,backgroundOpacity:a.df,charEdgeStyle:a.Yh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.rj,fontStyle:a.bold&&a.pf?3:a.bold?1:a.pf?2:0,textOpacity:a.Kh,windowColor:j4.windowColor,windowOpacity:j4.Mk};var b=c4(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Lv=function(a,b){var c={};g.Ga(c,c4(this,"display-settings"));g.Ga(c,a);b4(this,c,b);this.g.T("captionssettingschanged")};
g.h.Iv=function(){!this.D&&this.loaded&&(g.Jb(this.R,function(a,b){a.dispose();delete this.R[b]},this),this.QE())};
g.h.Wt=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.cd(b,-2,4);this.Lv({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&i4(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.A.wb&&h4(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.D)break;if(!g.Ca(b))break;if(g.Wb(b)){i4(this,null,!0);break}var d;c=O3(this.B.l,!0);for(var e=0;e<c.length;e++){var f=c[e];f.l!=b.languageCode||d&&f.B!=b.languageName||(d=b.translationLanguage?
Qxa(f,b.translationLanguage):f)}!d||d==this.l&&this.loaded||i4(this,d,!0)}else return this.loaded&&this.l&&this.l!=f4(this)?f3(this.l):{};return"";case "tracklist":return this.B?(0,g.G)(O3(this.B.l,!(!b||!b.includeAsr)),function(a){return f3(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":d=this.ks();if(g.FM(this.A)&&b&&g.Ca(b))if(b.reset)this.GD();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=Gya(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=Hya(b[c],d[c]);break;case "charEdgeStyle":var k=g.Z_[b[c]];f[c]=g.va(k)?k:d[c];break;case "fontSizeIncrement":f[c]=Iya(b[c],d[c]);break;case "fontFamilyOption":k=g.Y_[b[c]];f.fontFamily=
g.va(k)?k:d[c];break;case "fontStyle":k=g.$_[b[c]],f[c]=g.va(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.Lv(f,!0);d=this.ks()}d.fontFamilyOption=g.Ata[d.fontFamily];d.charEdgeStyle=g.Bta[d.charEdgeStyle];d.fontStyle=g.Cta[d.fontStyle];return d;case "sampleSubtitles":this.D||void 0==b||Fya(this,!!b);break;case "xmlTrack":b&&this.A.wb&&(this.D||i4(this,new g.CH({languageName:b.name}),!1,b.xml))}};
g.h.uM=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.A.wb&&a.push("stickyLoading","xmlTrack");return a};
g.h.vM=function(){var a=this.l;return a?{cc:a.D}:{}};
g.h.FE=function(){this.loaded&&this.l&&this.l!=f4(this)?(h4(this,"module-enabled",!1),this.unload(),e4(this,!0)&&i4(this,f4(this),!1)):i4(this,this.l==f4(this)?g4(this,!0):this.l,!0)};
g.h.iQ=function(){var a=this.l==f4(this);e4(this,a)?i4(this,this.g.getAudioTrack().co,!1):this.o.captionTracks.length&&(this.loaded&&this.unload(),this.QA()&&(a?i4(this,g4(this),!1):this.load()))};g.iY.captions=d4;})(_yt_player);
