(function(g){var window=this;var Nya=function(a,b,c,d){var e=b.Xb();g.U(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.bd(c,d?d:"mqdefault.jpg");var k=b instanceof g.jO?g.PV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.iQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.jO?b.Aa:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.Rk||g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.vl(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.kQ&&(c.playlist_length=b.getLength());a.update(c)},l4=function(a,b){g.mH.call(this,{G:"div",
da:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.created=!1},m4=function(a){g.W.call(this,{G:"div",
L:"ytp-upnext",P:{"aria-label":"{{aria_label}}"},N:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",N:[{G:"span",L:"ytp-upnext-header",aa:"Up Next"},{G:"span",L:"ytp-upnext-title",aa:"{{title}}"},{G:"span",L:"ytp-upnext-author",aa:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",P:{role:"button",href:"{{url}}","aria-label":"Play next video"},N:[{G:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},N:[{G:"circle",L:"ytp-svg-autoplay-circle",
P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",N:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",aa:"Auto-play is paused"}]}]});this.B=null;
var b=this.g["ytp-upnext-cancel"];this.B=new g.W({G:"button",da:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":"Cancel autoplay"},aa:"Cancel"});g.N(this,this.B);this.B.U("click",this.qQ,this);this.B.ua(b);this.o=a;this.J=this.g["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.H=new g.Ut(this.In,5E3,this);g.N(this,this.H);this.I=0;this.O(this.g["ytp-upnext-autoplay-icon"],"click",this.zS);this.oC();this.O(a,"autonavvisibility",this.oC);this.O(a,"mdxnowautoplaying",
this.PR);this.O(a,"mdxautoplaycanceled",this.QR);this.O(a,"mdxautoplayupnext",this.TE);3==this.o.Qa()&&(a=(a=g.$U(g.WU(this.o)))?a.oJ():null)&&this.TE(a)},Oya=function(a,b){a.C=b;
Nya(a,b,g.Y(a.o),"hqdefault.jpg")},n4=function(a,b){if(!a.A){g.TF("a11y-announce","Up Next "+a.C.title);
a.I=g.dG();a.A=new g.Ut((0,g.z)(a.jr,a,b),25);a.jr(b);var c=b||g.Y(a.o).experiments.l("autoplay_time")||1E4;a.o.va("onAutonavCoundownStarted",c)}g.hq(a.element,"ytp-upnext-autoplay-paused")},p4=function(a){o4(a);
a.I=g.dG();a.jr();g.S(a.element,"ytp-upnext-autoplay-paused")},o4=function(a){a.A&&(a.A.dispose(),a.A=null)},q4=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.o);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.C.Xb(),a.In(),a.D=new window.Notification("Up Next",{body:d.title,icon:d.bd(c)}),a.F=a.O(a.D,"click",a.pS),a.H.start())}o4(a);a.o.fk(!1,b)},Pya=function(a){l4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.A=new g.W({G:"div",L:"ytp-subscribe-card",N:[{G:"img",L:"ytp-author-image",P:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",N:[{G:"div",L:"ytp-author-name",aa:b.author},{G:"div",L:"html5-subscribe-button-container"}]}]});g.N(this,this.A);this.A.ua(this.element);this.B=new g.RY("Subscribe",null,"Unsubscribe",null,!0,!1,b.Nh,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.B);this.B.ua(this.A.g["html5-subscribe-button-container"]);this.hide()},r4=
function(a){var b=g.Y(a),c=g.tI||g.cf?{style:"will-change: opacity"}:void 0,d=b.g,e=["ytp-videowall-still"];
b.l&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",da:e,P:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},N:[{G:"div",L:"ytp-videowall-still-image",P:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",N:[{G:"span",L:"ytp-videowall-still-info-bg",N:[{G:"span",L:"ytp-videowall-still-info-content",P:c,N:[{G:"span",L:"ytp-videowall-still-info-title",aa:"{{title}}"},{G:"span",
L:"ytp-videowall-still-info-author",aa:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",aa:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",aa:"{{duration}}"}]}]}]},{G:"span",da:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],N:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",N:[" (",{G:"span",aa:"{{playlist_length}}"},")"]}]},{G:"span",da:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
N:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",aa:" (50+)"}]}]});this.C=d;this.o=a;this.A=null;this.B=new g.BF(this);g.N(this,this.B);this.U("click",this.F);this.U("keypress",this.H);this.B.O(a,"videodatachange",this.D);g.Y(a).X&&(a=a.app.fa,b=this.element,g.Pa(a.g,b),g.Sa(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.Ye(this,(0,g.z)(a.D,a,b)));this.D()},s4=function(a){l4.call(this,a,"videowall-endscreen");
this.K=a;this.F=0;this.B=[];this.H=this.D=this.C=null;this.I=this.R=!1;this.W=new g.BF(this);g.N(this,this.W);this.J=new g.Ut(g.Fa(g.S,this.element,"ytp-show-tiles"),0);g.N(this,this.J);var b=new g.W({G:"button",da:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":"Previous"},N:[g.LV()]});g.N(this,b);b.ua(this.element);b.U("click",this.lO,this);this.M=new g.gH({G:"div",L:"ytp-endscreen-content"});g.N(this,this.M);this.M.ua(this.element);b=new g.W({G:"button",da:["ytp-button","ytp-endscreen-next"],
P:{"aria-label":"Next"},N:[g.MV()]});g.N(this,b);b.ua(this.element);b.U("click",this.kO,this);this.A=new m4(a);g.N(this,this.A);g.tV(this.o,this.A.element,4);this.hide()},t4=function(a){return g.uV(a.o)&&a.Ax()&&!a.H},Qya=function(a,b){return(0,g.G)(b.suggestions,function(b){b=g.mY(b);
g.N(a,b);return b})},u4=function(a){var b=a.pu();
b!=a.R&&(a.R=b,a.o.T("autonavvisibility"))},v4=function(a){g.yV.call(this,a);
this.l=null;this.o=new g.BF(this);g.N(this,this.o);this.A=g.Y(a);Rya(a)?this.l=new s4(this.g):this.A.Ma?this.l=new Pya(this.g):this.l=new l4(this.g);g.N(this,this.l);g.tV(this.g,this.l.element,4);this.FD();this.o.O(a,"videodatachange",this.FD,this);this.o.O(a,"crn_endscreen",this.mM,this);this.o.O(a,"crx_endscreen",this.nM,this)},Rya=function(a){a=g.Y(a);
return a.hd&&!a.Ma};
g.p(l4,g.mH);l4.prototype.create=function(){this.created=!0};
l4.prototype.destroy=function(){this.created=!1};
l4.prototype.Ax=function(){return!1};
l4.prototype.pu=function(){return!1};g.p(m4,g.W);g.h=m4.prototype;g.h.In=function(){this.D&&(this.H.stop(),this.Da(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.oC=function(){g.lH(this,g.XU(this.o))};
g.h.pS=function(){window.focus();this.In()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.jr=function(a){a=a||g.Y(this.o).experiments.l("autoplay_time")||1E4;var b=Math.min(g.dG()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.o.Qa()?q4(this,!0):this.A&&this.A.start()};
g.h.zS=function(a){!g.Pd(this.B.element,g.pF(a))&&g.sX(a,this.o)&&q4(this)};
g.h.qQ=function(){g.YU(this.o,!0)};
g.h.PR=function(a){this.o.Qa();this.show();n4(this,a)};
g.h.TE=function(a){this.o.Qa();this.C&&this.C.Xb().videoId==a.Xb().videoId||Oya(this,a)};
g.h.QR=function(){this.o.Qa();o4(this);this.hide()};
g.h.V=function(){o4(this);this.In();g.W.prototype.V.call(this)};g.p(Pya,l4);g.p(r4,g.W);r4.prototype.wk=function(){g.vV(this.o,this.element);var a=this.A.Xb().videoId,b=this.A.getPlaylistId();g.QZ(this.o.app,a,this.A.Md,b,void 0,void 0,void 0)};
r4.prototype.F=function(a){g.sX(a,this.o,this.C,this.A.Md||void 0)&&this.wk()};
r4.prototype.H=function(a){switch(a.keyCode){case 13:case 32:g.uF(a)||(this.wk(),g.tF(a))}};
r4.prototype.D=function(){var a=this.o.getVideoData(),b=g.Y(this.o);this.C=a.isDni?!1:b.g};g.p(s4,l4);g.h=s4.prototype;g.h.create=function(){l4.prototype.create.call(this);var a=this.o.getVideoData();a&&(this.C=Qya(this,a),this.D=a);this.Gg();this.W.O(this.o,"appresize",this.Gg);this.W.O(this.o,"onVideoAreaChange",this.Gg);this.W.O(this.o,"videodatachange",this.mO);this.W.O(this.o,"autonavchange",this.oB);this.W.O(this.o,"autonavcancel",this.jO);this.W.O(this.element,"transitionend",this.RT)};
g.h.destroy=function(){g.DF(this.W);g.$e(this.B);this.B=[];this.C=null;l4.prototype.destroy.call(this);g.hq(this.element,"ytp-show-tiles");this.J.stop()};
g.h.Ax=function(){return 1!=this.D.autonavState};
g.h.show=function(){l4.prototype.show.call(this);g.hq(this.element,"ytp-show-tiles");g.Y(this.o).l?g.Wt(this.J):this.J.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.YU(this.o,!1);t4(this)?(u4(this),2==this.D.autonavState?g.Y(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.Hi()?q4(this.A,!0):n4(this.A):3==this.D.autonavState&&p4(this.A)):(g.YU(this.o,!0),u4(this))};
g.h.hide=function(){l4.prototype.hide.call(this);p4(this.A);u4(this)};
g.h.RT=function(a){g.pF(a)==this.element&&this.Gg()};
g.h.Gg=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.lV(this.K,!0),b=g.zH(this.K);b&&(b=b.qd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,v=b<=f-2&&n>=r*m,D=e<=k-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&D)n-=q*m,e+=2;else if(v)n-=r*m,b+=2;else if(D)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.cd(a.width/m||1,1,1.21);n*=g.cd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Gh(a,m,n);g.nh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});Oya(this.A,this.C[0]);g.U(this.element,"ytp-endscreen-takeover",t4(this));u4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&
2>f?0==k&&0==f&&(r=2):r=2),q=g.dd(q+this.F,l),0!=r){v=this.B[c];v||(v=new r4(this.o),this.B[c]=v,a.appendChild(v.element));D=Math.floor(n*k/e);var H=Math.floor(m*f/b),L=Math.floor(n*(k+r)/e)-D-4,T=Math.floor(m*(f+r)/b)-H-4;g.uh(v.element,H,D);g.Gh(v.element,T,L);g.nh(v.element,"transitionDelay",(k+f)/20+"s");g.U(v.element,"ytp-videowall-still-mini",1==r);g.U(v.element,"ytp-videowall-still-large",2<r);r=v;q=this.C[q];r.A!=q&&(r.A=q,Nya(r,q,g.Y(r.o),g.fq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),v=(q=q.Md)&&q.itct)&&(q=r.o,g.Y(q).X&&(q=q.app.fa,r=r.element,D=r.getAttribute("data-visual-id"),g.Pa(q.g,r),g.wV(q,"onLogServerVeCreated",{id:D,tracking_params:v})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.B.length-1;b>=c;b--)e=this.B[b],g.Jd(e.element),g.Ze(e);this.B.length=c}};
g.h.mO=function(){var a=this.o.getVideoData();this.D!=a&&(this.F=0,this.C=Qya(this,a),this.D=a,this.Gg())};
g.h.kO=function(){this.F+=this.B.length;this.Gg()};
g.h.lO=function(){this.F-=this.B.length;this.Gg()};
g.h.qL=function(){return!!this.A.A};
g.h.oB=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,o4(this.A),this.l&&this.Gg()):(this.I=!0,this.l&&t4(this)&&(2==a?n4(this.A):3==a&&p4(this.A)))};
g.h.jO=function(a){if(a){for(a=0;a<this.B.length;a++)g.xV(this.K,this.B[a].element,!0);this.oB(1)}else this.H=null,this.I=!1;this.Gg()};
g.h.pu=function(){return this.l&&t4(this)};g.p(v4,g.yV);g.h=v4.prototype;g.h.PA=function(){var a=this.g.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!Rya(this.g)||b;a=g.GO(a,"ypc_module");var c=g.RZ(this.g.app);return b&&!a&&!c};
g.h.OA=function(){return this.l.pu()};
g.h.mL=function(){return this.OA()?this.l.qL():!1};
g.h.V=function(){g.rV(this.g,"endscreen");g.yV.prototype.V.call(this)};
g.h.load=function(){g.yV.prototype.load.call(this);this.l.show()};
g.h.unload=function(){g.yV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.mM=function(a){this.PA()&&(this.l.created||this.l.create(),"load"==a.getId()&&this.load())};
g.h.nM=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.FD=function(){g.rV(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0);a=new g.fQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.N(this,a);var b=new g.fQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.N(this,b);g.oV(this.g,[a,b])};g.iY.endscreen=v4;})(_yt_player);
