(function(g){var window=this;var tza=function(a,b){return g.Tb(a,b)},W4=function(a){g.zm(a,"zx",g.xb());
return a},X4=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Cm(a.g,b,c)},uza=function(a,b){var c=[];
g.mk(b,function(a){try{var b=g.$C.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.ZC(b)&&c.push(a):c.push(a)},a);
return c},vza=function(a,b){var c=uza(a,b);
(0,g.B)(c,function(a){g.$C.prototype.remove.call(this,a)},a)},wza=function(a){if(a.zd){if(a.zd.locationOverrideToken)return{locationOverrideToken:a.zd.locationOverrideToken};
if(null!=a.zd.latitudeE7&&null!=a.zd.longitudeE7)return{latitudeE7:a.zd.latitudeE7,longitudeE7:a.zd.longitudeE7}}return null},xza=function(a,b,c,d){var e=new g.qm(null,void 0);
a&&g.rm(e,a);b&&g.sm(e,b);c&&g.tm(e,c);d&&g.um(e,d);return e},yza=function(a){g.PF[a]&&(a=g.PF[a],(0,g.B)(a,function(a){g.NF[a]&&delete g.NF[a]}),a.length=0)},zza=function(a){var b=g.MF();
if(b)if(b.clear(a),a)yza(a);else for(var c in g.PF)yza(c)},Y4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.km;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Aza(this,a.capabilities||""),Bza(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Aza=function(a,b){a.capabilities.clear();
(0,g.Kd)(b.split(","),g.Fa(tza,Cza)).forEach(function(b){a.capabilities.add(b)})},Bza=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},Z4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},$4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Dza=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Eza=function(a){return new Z4(a)},Fza=function(a){return g.za(a)?(0,g.G)(a,Eza):[]},a5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},b5=function(a){return g.za(a)?"["+(0,g.G)(a,a5).join(",")+"]":"null"},c5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Gza=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},d5=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},e5=function(a,b){return g.La(a,function(a){return $4(a,b)})},Hza=function(){var a=(0,g.IG)();
a&&vza(a,a.g.Pd(!0))},f5=function(){var a=g.LG("yt-remote-connected-devices")||[];
g.gb(a);return a},Iza=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},Jza=function(a){g.KG("yt-remote-connected-devices",a,86400)},h5=function(){if(g5)return g5;
var a=g.LG("yt-remote-device-id");a||(a=c5(),g.KG("yt-remote-device-id",a,31536E3));for(var b=f5(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return g5=d},i5=function(){var a=f5(),b=h5();
g.Pa(a,b);g.NG()&&g.jb(a,b);a=Iza(a);if(g.Qa(a))try{g.vG("remote_sid")}catch(c){}else try{g.uG("remote_sid",a.join(","),-1)}catch(c){}},Kza=function(){return g.LG("yt-remote-session-browser-channel")},Lza=function(){return g.LG("yt-remote-local-screens")||[]},Mza=function(){g.KG("yt-remote-lounge-token-expiration",!0,86400)},Nza=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(Lza(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.Zl)(c,function(a){return!g.Pa(b,a)})&&Mza();
g.KG("yt-remote-local-screens",a,31536E3)},Oza=function(a,b){g.KG("yt-remote-session-browser-channel",a);
g.KG("yt-remote-session-screen-id",b);var c=f5(),d=h5();g.Pa(c,d)||c.push(d);Jza(c);i5()},j5=function(a){a||(g.MG("yt-remote-session-screen-id"),g.MG("yt-remote-session-video-id"));
i5();a=f5();g.Ua(a,h5());Jza(a)},Pza=function(){if(!k5){var a=g.kD();
a&&(k5=new g.UC(a))}return k5?!!k5.get("yt-remote-use-staging-server"):!1},Qza=function(){var a=window.document.createElement("a");
g.Zc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},Rza=function(a,b){var c=g.Dd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.ad(c,g.be("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Sza=function(){var a=Qza(),b=window.document.getElementById(a),c=b&&g.YE(b,"loaded");
c||b&&!c||(b=Rza(a,function(){g.YE(b,"loaded")||(g.XE(b,"loaded","true"),g.TF(a),g.TD(g.Fa(zza,a),0))}))},l5=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},Tza=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},m5=function(a){a.length?Uza(a.shift(),function(){m5(a)}):n5()},Vza=function(a){return"chrome-extension://"+a+o5},Uza=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},p5=function(a){return 0<=window.navigator.userAgent.indexOf(a)},n5=function(){var a=Tza();
a&&a(!1,"No cast extension found")},q5=function(){if(Wza){var a=2,b=Tza(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Uza("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",n5,c)}},Xza=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(q5(),a({command:"cast.sender.init"}))},Yza=function(){q5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);m5(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+o5,"//www.gstatic.com/eureka/clank"+o5])},r5=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.pd=b;this.B=(0,g.z)(this.tJ,this);this.g=!1;this.l=0;this.o=this.Ba=null;this.A=[]},s5=function(){},t5=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Gm(this);this.l=new g.qg;this.l.setInterval(250)},$za=function(a,b,c){a.Hj=1;
a.jh=W4(b.clone());a.Ni=c;a.B=!0;Zza(a,null)},u5=function(a,b,c,d,e){a.Hj=1;
a.jh=W4(b.clone());a.Ni=null;a.B=c;e&&(a.OD=!1);Zza(a,d)},Zza=function(a,b){a.uk=(0,g.F)();
v5(a);a.Ih=a.jh.clone();X4(a.Ih,"t",a.C);a.Nm=0;a.Qc=a.g.Lr(a.g.Em()?b:null);0<a.ys&&(a.Jp=new g.Qk((0,g.z)(a.dF,a,a.Qc),a.ys));a.W.U(a.Qc,"readystatechange",a.NU);var c=a.li?g.ac(a.li):{};a.Ni?(a.wq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.Ih,a.wq,a.Ni,c)):(a.wq="GET",a.OD&&!g.zd&&(c.Connection="close"),a.Qc.send(a.Ih,a.wq,null,c));a.g.vf(1)},cAa=function(a,b,c){for(var d=!0;!a.Vh&&a.Nm<c.length;){var e=aAa(a,c);
if(e==w5){4==b&&(a.kh=4,x5(15),d=!1);break}else if(e==bAa){a.kh=4;x5(16);d=!1;break}else y5(a,e)}4==b&&0==c.length&&(a.kh=1,x5(17),d=!1);a.Bf=a.Bf&&d;d||(z5(a),A5(a))},aAa=function(a,b){var c=a.Nm,d=b.indexOf("\n",c);
if(-1==d)return w5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return bAa;d+=1;if(d+c>b.length)return w5;var e=b.substr(d,c);a.Nm=d+c;return e},eAa=function(a,b){a.uk=(0,g.F)();
v5(a);var c=b?window.location.hostname:"";a.Ih=a.jh.clone();g.zm(a.Ih,"DOMAIN",c);g.zm(a.Ih,"t",a.C);try{a.Cf=new window.ActiveXObject("htmlfile")}catch(n){z5(a);a.kh=7;x5(22);A5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in B5)k=B5[l];else if(l in dAa)k=B5[l]=dAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=B5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.bd(g.wc("b/12014412"),d);a.Cf.open();a.Cf.write(g.Tc(c));a.Cf.close();a.Cf.parentWindow.m=(0,g.z)(a.UT,a);a.Cf.parentWindow.d=(0,g.z)(a.aD,a,!0);a.Cf.parentWindow.rpcClose=(0,g.z)(a.aD,a,!1);c=a.Cf.createElement("DIV");a.Cf.parentWindow.document.body.appendChild(c);d=g.Kc(a.Ih.toString());d=g.qb(g.Hc(d));d=g.bd(g.wc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Tc(d);
a.g.vf(1)},v5=function(a){a.Yv=(0,g.F)()+a.A;
fAa(a,a.A)},fAa=function(a,b){if(null!=a.Lk)throw Error("WatchDog timer not null");
a.Lk=C5((0,g.z)(a.mU,a),b)},D5=function(a){a.Lk&&(g.w.clearTimeout(a.Lk),a.Lk=null)},A5=function(a){a.g.kz()||a.Vh||a.g.wp(a)},z5=function(a){D5(a);
g.Ze(a.Jp);a.Jp=null;a.l.stop();g.Mm(a.W);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.Cf&&(a.Cf=null)},y5=function(a,b){try{a.g.TC(a,b),a.g.vf(4)}catch(c){}},hAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;gAa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){hAa(a,b,c,d,f)},f)})}},gAa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{E5(d),c(!0)}catch(e){}};
d.onerror=function(){try{E5(d),c(!1)}catch(e){}};
d.onabort=function(){try{E5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{E5(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},E5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},iAa=function(a){this.g=a;
this.l=new s5},jAa=function(a){var b=F5(a.g,a.Uk,"/mail/images/cleardot.gif");
W4(b);hAa(b.toString(),5E3,(0,g.z)(a.EI,a),3,2E3);a.vf(1)},H5=function(a){var b=a.g.H;
if(null!=b)x5(5),b?(x5(11),G5(a.g,a,!1)):(x5(12),G5(a.g,a,!0));else if(a.re=new t5(a,void 0,void 0,void 0),a.re.li=a.ws,b=a.g,b=F5(b,b.Em()?a.zl:null,a.xs),x5(5),!g.xd||g.qc(10))X4(b,"TYPE","xmlhttp"),u5(a.re,b,!1,a.zl,!1);else{X4(b,"TYPE","html");var c=a.re;a=!!a.zl;c.Hj=3;c.jh=W4(b.clone());eAa(c,a)}},I5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new s5;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},kAa=function(a,b){this.g=a;
this.map=b;this.context=null},lAa=function(a){g.af.call(this,"statevent",a)},mAa=function(a,b){g.af.call(this,"timingevent",a);
this.size=b},nAa=function(a){g.af.call(this,"serverreachability",a)},qAa=function(a){oAa(a);
if(3==a.g){var b=a.jm++,c=a.eo.clone();g.zm(c,"SID",a.o);g.zm(c,"RID",b);g.zm(c,"TYPE","terminate");J5(a,c);b=new t5(a,a.o,b,void 0);b.Hj=2;b.jh=W4(c.clone());(new window.Image).src=b.jh;b.uk=(0,g.F)();v5(b)}pAa(a)},rAa=function(a){a.bJ(1,0);
a.eo=F5(a,null,a.us);K5(a)},oAa=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.tc&&(a.tc.cancel(),a.tc=null);a.qg&&(g.w.clearTimeout(a.qg),a.qg=null);L5(a);a.Vd&&(a.Vd.cancel(),a.Vd=null);a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},sAa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new kAa(a.JP++,b));2!=a.g&&3!=a.g||K5(a)},K5=function(a){a.Vd||a.eh||(a.eh=C5((0,g.z)(a.YC,a),0),a.tj=0)},uAa=function(a,b){if(1==a.g){if(!b){a.jm=Math.floor(1E5*Math.random());
var c=a.jm++,d=new t5(a,"",c,void 0);d.li=null;var e=M5(a),f=a.eo.clone();g.zm(f,"RID",c);g.zm(f,"CVER","1");J5(a,f);$za(d,f,e);a.Vd=d;a.g=2}}else 3==a.g&&(b?tAa(a,b):0==a.l.length||a.Vd||tAa(a))},tAa=function(a,b){if(b)if(6<a.Xh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.jm-1;var d=M5(a)}else c=b.D,d=b.Ni;else c=a.jm++,d=M5(a);var e=a.eo.clone();g.zm(e,"SID",a.o);g.zm(e,"RID",c);g.zm(e,"AID",a.Vj);J5(a,e);c=new t5(a,a.o,c,a.tj+1);c.li=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Vd=c;$za(c,e,d)},J5=function(a,b){if(a.od){var c=a.od.Ry();
c&&g.Jb(c,function(a,c){g.zm(b,c,a)})}},M5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Xh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Xh?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},vAa=function(a){a.tc||a.qg||(a.D=1,a.qg=C5((0,g.z)(a.XC,a),0),a.hj=0)},N5=function(a){if(a.tc||a.qg||3<=a.hj)return!1;
a.D++;a.qg=C5((0,g.z)(a.XC,a),wAa(a,a.hj));a.hj++;return!0},G5=function(a,b,c){a.uq=c;
a.Pf=b.Bg;a.C||rAa(a)},L5=function(a){null!=a.Zh&&(g.w.clearTimeout(a.Zh),a.Zh=null)},wAa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},O5=function(a,b){if(2==b||9==b){var c=null;
a.od&&(c=null);var d=(0,g.z)(a.FV,a);c||(c=new g.qm("//www.google.com/images/cleardot.gif"),W4(c));gAa(c.toString(),1E4,d)}else x5(2);xAa(a,b)},xAa=function(a,b){a.g=0;
a.od&&a.od.Lx(b);pAa(a);oAa(a)},pAa=function(a){a.g=0;
a.Pf=-1;if(a.od)if(0==a.A.length&&0==a.l.length)a.od.yr();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.od.yr(b)}},F5=function(a,b,c){var d=g.Am(c);
if(""!=d.l)b&&g.sm(d,b+"."+d.l),g.tm(d,d.B);else{var e=window.location;d=xza(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.kl&&g.Jb(a.kl,function(a,b){g.zm(d,b,a)});
g.zm(d,"VER",a.Xh);J5(a,d);return d},C5=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},x5=function(a){P5.dispatchEvent(new lAa(P5,a))},yAa=function(){},zAa=function(a,b){this.action=a;
this.params=b||{}},Q5=function(a,b){g.M.call(this);
this.g=new g.Ut(this.KT,0,this);g.N(this,this.g);this.pd=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},R5=function(a,b,c){this.J=a;
this.C=b;this.o=new g.TC;this.l=new Q5(this.lW,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.K=c||!1},AAa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.uq,sessionId:a.g.o,arrayId:a.g.Vj}},BAa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&uAa(a.g),qAa(a.g));a.F=0},S5=function(a){return!!a.g&&3==a.g.g},CAa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},T5=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Gg(a)||"";b&&(this.port=":"+b);this.domain=g.Fg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},U5=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Pg(c+b,{})},V5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),wd:g.Fa(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.jE(b,a)},GAa=function(){var a=DAa;
EAa();W5.push(a);FAa(W5)},X5=function(a,b){EAa();
var c=W5,d=HAa(a,String(b));g.Qa(c)?IAa(d):(FAa(c),(0,g.B)(c,function(a){a(d)}))},EAa=function(){W5||(W5=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",W5,void 0))},IAa=function(a){var b=(Y5+1)%50;
Y5=b;Z5[b]=a;$5||($5=49==b)},FAa=function(a){var b=Z5;
if(b[0]){var c=Y5,d=$5?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
Z5=Array(50);Y5=-1;$5=!1}},HAa=function(a,b){var c=((0,g.F)()-JAa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},a6=function(a){g.EF.call(this);
this.D=a;this.g=[]},KAa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},LAa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Kd)(a.g,function(a){return!!d5(b,a)});
for(var d=0,e=b.length;d<e;d++)c=KAa(a,b[d])||c;return c},MAa=function(a,b){var c=a.g.length;
a.g=(0,g.Kd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},b6=function(a,b,c,d){g.EF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ba=window.NaN},d6=function(a){a6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;c6(this);this.info("Initializing with "+b5(this.g))},NAa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=U5(a.o,"/pairing/get_lounge_token_batch");
V5(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.GJ,a),(0,g.z)(a.FJ,a))}},c6=function(a){var b=Fza(Lza());
b=(0,g.Kd)(b,function(a){return!a.uuid});
return LAa(a,b)},e6=function(a,b){Nza((0,g.G)(a.g,Dza));
b&&Mza()},g6=function(a,b){g.EF.call(this);
this.C=b;var c=g.LG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;f6("Initialized with "+g.xg(this.g))},OAa=function(a,b,c){var d=U5(a.B,"/pairing/get_screen_availability");
V5(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},h6=function(a,b){a:if(g.Nb(b)!=g.Nb(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(f6("Updated online screens: "+g.xg(a.g)),a.g=b,a.T("screenChange"));PAa(a)},i6=function(a){(0,window.isNaN)(a.o)||g.VD(a.o);
a.o=g.TD((0,g.z)(a.lv,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},f6=function(a){X5("OnlineScreenService",a)},QAa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.fc("Requesting availability of screen w/o lounge token.")});
return b},PAa=function(a){a=g.Qb(g.Kb(a.g,function(a){return a}));
g.gb(a);a.length?g.KG("yt-remote-online-screen-ids",a.join(","),60):g.MG("yt-remote-online-screen-ids")},j6=function(a){a6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};RAa(this)},TAa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ie();if(k=(c?e5(k,c):null)||e5(k,b)){k.uuid=b;var l=k6(a,k);OAa(a.l,l,function(a){e(a?l:null)})}else c?SAa(a,c,(0,g.z)(function(a){var f=k6(this,new Z4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));OAa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},UAa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},SAa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.jE(U5(a.C,"/pairing/get_lounge_token_batch"),e)},VAa=function(a){a.g=a.o.ie();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+b5(a.g))},RAa=function(a){l6(a);
a.o=new d6(a.C);a.o.subscribe("screenChange",(0,g.z)(a.VJ,a));VAa(a);a.A=Fza(g.LG("yt-remote-automatic-screen-cache")||[]);l6(a);a.info("Initializing automatic screens: "+b5(a.A));a.l=new g6(a.C,(0,g.z)(a.ie,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.T("onlineScreenChange")},a))},k6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=e5(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.KG("yt-remote-automatic-screen-cache",(0,g.G)(a.A,Dza)));l6(a);a.B[b.uuid]=b.id;g.KG("yt-remote-device-id-map",a.B,31536E3);return b},l6=function(a){a.B=g.LG("yt-remote-device-id-map")||{}},m6=function(a,b,c){g.EF.call(this);
this.K=c;this.H=a;this.l=b;this.o=null},n6=function(a,b){X5(a.K,b)},o6=function(a,b){m6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.rW,this);this.B=(0,g.z)(this.yU,this);this.A=g.TD((0,g.z)(function(){WAa(this,null)},this),12E4)},XAa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.xg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){n6(this,"Failed to send message: getMdxSessionStatus.")},a)):n6(a,"Sending yt message without session: "+g.xg(b))},WAa=function(a,b){g.VD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.xp,a),d=(0,g.z)(a.pe,a);a.bz(b,c,d,5)}}else a.pe(Error("Waiting for session status timed out."))},p6=function(a,b,c){m6.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.M=c;this.B=null;this.D=g.y;this.C=window.NaN;this.J=(0,g.z)(this.uW,this);this.g=g.y},YAa=function(a){a.g=a.H.kF(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.xp(a)},a),(0,g.z)(function(a){this.g=g.y;
this.pe(a)},a))},ZAa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.M;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Pza()&&(b.env_useStageMdx=1);return g.Ng(b)},q6=function(a,b){m6.call(this,a,b,"ManualSession");
this.g=g.TD((0,g.z)(this.Xj,this,null),150)},r6=function(a,b,c,d){g.EF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.XS,this)},$Aa=function(a,b){return b?g.La(a.o,function(a){return $4(b,a.label)},a):null},s6=function(a){X5("Controller",a)},DAa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},t6=function(a){return a.B||!!a.o.length||!!a.g},u6=function(a,b,c){b!=a.g&&(g.Ze(a.g),(a.g=b)?(c?a.T("yt-remote-cast2-receiver-resumed",b.l):a.T("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.VC,a,b)),b.o?a.T("yt-remote-cast2-session-change",b.o):c&&a.g.Xj(null)):a.T("yt-remote-cast2-session-change",null))},aBa=function(a){var b=a.l.jF(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&$4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=$Aa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},gBa=function(a,b,c,d,e,f,k){bBa()?cBa(b,e,f,k)&&(w6(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?dBa(a,c):(window.__onGCastApiAvailable=function(b,d){b?dBa(a,c):(x6("Failed to load cast API: "+d),y6(!1),w6(!1),g.MG("yt-remote-cast-available"),g.MG("yt-remote-cast-receiver"),eBa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Sza():p5("CriOS")?Xza():p5("Android")&&p5("Chrome/")&&window.navigator.presentation?Yza():window.chrome&&window.navigator.presentation&&!p5("Edge")?(q5(),m5(fBa.map(Vza))):n5())):v6("Cannot initialize because not running Chrome")},eBa=function(){v6("dispose");
var a=z6();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);hBa(!1);g.RF(A6);A6.length=0},B6=function(){return!!g.LG("yt-remote-cast-installed")},iBa=function(){var a=g.LG("yt-remote-cast-receiver");
return a?a.friendlyName:null},jBa=function(){v6("clearCurrentReceiver");
g.MG("yt-remote-cast-receiver")},kBa=function(){return B6()?z6()?z6().getCastSession():(x6("getCastSelector: Cast is not initialized."),null):(x6("getCastSelector: Cast API is not installed!"),null)},D6=function(){B6()?z6()?C6()?(v6("Requesting cast selector."),z6().requestSession()):(v6("Wait for cast API to be ready to request the session."),A6.push(g.QF("yt-remote-cast2-api-ready",D6))):x6("requestCastSelector: Cast is not initialized."):x6("requestCastSelector: Cast API is not installed!")},E6=
function(a,b){C6()?z6().setConnectedScreenStatus(a,b):x6("setConnectedScreenStatus called before ready.")},bBa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.tI||a},lBa=function(a,b){z6().init(a,b)},cBa=function(a,b,c,d){var e=!1;
z6()||(a=new r6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.KG("yt-remote-cast-available",a);g.UF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){v6("onReceiverSelected: "+a.friendlyName);
g.KG("yt-remote-cast-receiver",a);g.UF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){v6("onReceiverResumed: "+a.friendlyName);
g.KG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){v6("onSessionChange: "+a5(a));
a||g.MG("yt-remote-cast-receiver");g.UF("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
v6("cloudview.createSingleton_: "+e);return e},z6=function(){return g.x("yt.mdx.remote.cloudview.instance_")},dBa=function(a,b){y6(!0);
w6(!1);lBa(a,function(a){a?(hBa(!0),g.TF("yt-remote-cast2-api-ready")):(x6("Failed to initialize cast API."),y6(!1),g.MG("yt-remote-cast-available"),g.MG("yt-remote-cast-receiver"),eBa());b(a)})},v6=function(a){X5("cloudview",a)},x6=function(a){X5("cloudview",a)},y6=function(a){v6("setCastInstalled_ "+a);
g.KG("yt-remote-cast-installed",a)},C6=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},hBa=function(a){v6("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},w6=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},F6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Sf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},G6=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Sf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},H6=function(a){return a.kb()?((0,g.F)()-a.D)/1E3:0},I6=function(a,b){a.F=b;
a.D=(0,g.F)()},J6=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},K6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&G6(a)},L6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.l);b.hasPrevious=a.Sf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},N6=function(a,b){g.EF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.jC;this.o=this.l=null;this.H=(0,g.z)(this.tQ,this);this.D=(0,g.z)(this.pm,this);this.F=(0,g.z)(this.sQ,this);this.I=(0,g.z)(this.FQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.gw,this),mBa(this))):c=3;0!=c&&(b?this.gw(c):g.TD((0,g.z)(function(){this.gw(c)},this),0));
var d=kBa();d&&M6(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},O6=function(a){return new F6(a.A.getPlayerContextData())},mBa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.RS,a),this))},a)},nBa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},P6=function(a,b){50>a.B.Bc()&&g.lC(a.B,b)},R6=function(a,b,c){var d=O6(a);
I6(d,c);-1E3!=d.g&&(d.g=b);Q6(a,d)},S6=function(a,b,c){a.A.sendMessage(b,c)},Q6=function(a,b){nBa(a);
a.A.setPlayerContextData(L6(b));mBa(a)},M6=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.pm(null));
a.o=b;a.o&&(X5("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.pm(a.o.media[0]))},oBa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=O6(a);b.contentId!=d.videoId&&X5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;I6(d,a.l.getEstimatedTime());Q6(a,d)}else X5("CP","No cast media video. Ignoring state update.")},T6=function(a,b,c){return(0,g.z)(function(a){this.fc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.fc("Retrying "+b+" using MDx browser channel."),S6(this,b,c))},a)},U6=function(a,b,c){g.EF.call(this);
this.B=window.NaN;this.M=!1;this.I=this.H=this.J=this.K=window.NaN;this.R=[];this.A=this.D=this.o=this.Za=this.g=null;this.ra=a;this.R.push(g.nF(window,"beforeunload",(0,g.z)(this.xJ,this)));this.l=[];this.Za=new F6;this.Y=b.id;this.g=pBa(this,c);this.g.subscribe("handlerOpened",this.xQ,this);this.g.subscribe("handlerClosed",this.uQ,this);this.g.subscribe("handlerError",this.vQ,this);this.g.subscribe("handlerMessage",this.wQ,this);CAa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.NG()&&g.KG("yt-remote-session-video-id",a)},this)},V6=function(a){X5("conn",a)},pBa=function(a,b){return new R5(U5(a.ra,"/bc"),b)},W6=function(a,b){a.T("proxyStateChange",b)},qBa=function(a){a.B=g.TD((0,g.z)(function(){V6("Connecting timeout");
this.C(1)},a),2E4)},X6=function(a){g.VD(a.B);
a.B=window.NaN},Y6=function(a){g.VD(a.K);
a.K=window.NaN},rBa=function(a){Z6(a);
a.J=g.TD((0,g.z)(function(){$6(this,"getNowPlaying")},a),2E4)},Z6=function(a){g.VD(a.J);
a.J=window.NaN},tBa=function(a,b){b&&(X6(a),Y6(a));
b==(S5(a.g)&&(0,window.isNaN)(a.B))?b&&(W6(a,1),$6(a,"getSubtitlesTrack")):b?(a.X()&&a.Za.reset(),W6(a,1),$6(a,"getNowPlaying"),sBa(a)):a.C(1)},uBa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Wb(b.params)?a.Za.l=null:a.Za.l=b.params,a.T("remotePlayerChange"))},vBa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;K6(a.Za,c,d);a.T("remoteQueueChange")},xBa=function(a,b){b.params=b.params||{};
vBa(a,b);wBa(a,b);a.T("autoplayDismissed")},wBa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
I6(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?rBa(a):Z6(a);
a.T("remotePlayerChange")},yBa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);I6(a.Za,(0,window.isNaN)(c)?0:c);a.T("remotePlayerChange")}},zBa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.T("remotePlayerChange")},ABa=function(a,b){a.D=b.params.videoId;
a.T("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},BBa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Sf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.T("previousNextChange")},sBa=function(a){g.VD(a.I);
a.I=g.TD((0,g.z)(a.C,a,1),864E5)},$6=function(a,b,c){c?V6("Sending: action="+b+", params="+g.xg(c)):V6("Sending: action="+b);
a.g.sendMessage(b,c)},a7=function(a){a6.call(this,"ScreenServiceProxy");
this.dd=a;this.l=[];this.l.push(this.dd.$_s("screenChange",(0,g.z)(this.pW,this)));this.l.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.sS,this)))},GBa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ND("MDX_CONFIG")||b;Hza();i5();b7||(b7=new T5(b?b.loungeApiHost:void 0),Pza()&&(b7.g="/api/loungedev"));c7||(c7=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",c7,void 0));CBa();var c=d7();if(!c){var d=new j6(b7);g.wa("yt.mdx.remote.screenService_",d,void 0);c=d7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);gBa(a,d,function(a){a?e7()&&E6(e7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.UF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),f7("Initializing: "+g.xg(b)),g7.push(g.QF("yt-remote-cast2-availability-change",function(){g.UF("yt-remote-receiver-availability-change")})),g7.push(g.QF("yt-remote-cast2-receiver-selected",function(){h7(null);
g.UF("yt-remote-auto-connect","cast-selector-receiver")})),g7.push(g.QF("yt-remote-cast2-receiver-resumed",function(){g.UF("yt-remote-receiver-resumed","cast-selector-receiver")})),g7.push(g.QF("yt-remote-cast2-session-change",DBa)),g7.push(g.QF("yt-remote-connection-change",function(a){a?E6(e7(),"YouTube TV"):i7()||(E6(null,null),jBa())})),a=j7(),b.isAuto&&(a.id+="#dial"),g.KF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),f7(" -- with channel params: "+
g.xg(a)),EBa(a),c.start(),e7()||FBa())},IBa=function(){var a=HBa();
B6()&&g.LG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},HBa=function(){var a=d7().dd.$_gos();
var b=k7();b&&l7()&&(d5(a,b)||a.push(b));return Gza(a)},m7=function(){var a=JBa();
!a&&B6()&&iBa()&&(a={key:"cast-selector-receiver",name:iBa()});return a},JBa=function(){var a=HBa(),b=k7();
b||(b=i7());return g.La(a,function(a){return b&&$4(b,a.key)?!0:!1})},k7=function(){var a=e7();
if(!a)return null;var b=d7().ie();return e5(b,a)},DBa=function(a){f7("remote.onCastSessionChange_: "+a5(a));
if(a){var b=k7();b&&b.id==a.id?E6(b.id,"YouTube TV"):(b&&n7(),o7(a,1))}else l7()&&n7()},n7=function(){C6()?z6().stopSession():x6("stopSession called before API ready.");
var a=l7();a&&(a.disconnect(1),p7(null))},q7=function(){var a=l7();
return!!a&&3!=a.getProxyState()},f7=function(a){X5("remote",a)},d7=function(){if(!r7){var a=g.x("yt.mdx.remote.screenService_");
r7=a?new a7(a):null}return r7},e7=function(){return g.x("yt.mdx.remote.currentScreenId_")},KBa=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},LBa=function(){return g.x("yt.mdx.remote.connectData_")},h7=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},l7=function(){return g.x("yt.mdx.remote.connection_")},p7=function(a){var b=l7();
h7(null);a||KBa("");g.wa("yt.mdx.remote.connection_",a,void 0);c7&&((0,g.B)(c7,function(b){b(a)}),c7.length=0);
b&&!a?g.UF("yt-remote-connection-change",!1):!b&&a&&g.UF("yt-remote-connection-change",!0)},i7=function(){var a=g.NG();
if(!a)return null;var b=d7().ie();return e5(b,a)},o7=function(a,b){k7()&&k7();
KBa(a.id);var c=new U6(b7,a,j7());c.connect(b,LBa());c.subscribe("beforeDisconnect",function(a){g.UF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){l7()&&p7(null)});
p7(c)},FBa=function(){var a=i7();
a?(f7("Resume connection to: "+a5(a)),o7(a,0)):(j5(),jBa(),f7("Skipping connecting because no session screen found."))},CBa=function(){var a=j7();
if(g.Wb(a)){a=h5();var b=g.LG("yt-remote-session-name")||"",c=g.LG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},j7=function(){return g.x("yt.mdx.remote.channelParams_")||{}},EBa=function(a){a?(g.KG("yt-remote-session-app",a.app),g.KG("yt-remote-session-name",a.name)):(g.MG("yt-remote-session-app"),g.MG("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},s7=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.BF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.MR);this.o.O(b,"captionschanged",this.rQ);this.o.O(b,"captionssettingschanged",this.xE);this.o.O(b,"videoplayerreset",this.yp);this.o.O(b,"mdxautoplaycancel",this.DI);this.R=this.o.O(b,"onVolumeChange",this.FC);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.SC,this);c.subscribe("remotePlayerChange",this.sm,this);c.subscribe("remoteQueueChange",this.yp,this);c.subscribe("autoplayUpNext",this.qC,
this);c.subscribe("previousNextChange",this.PC,this);c.subscribe("nowAutoplaying",this.HC,this);c.subscribe("autoplayDismissed",this.pC,this);this.suggestion=null;this.H=new g.rP(64);this.A=new g.Ut(this.tE,500,this);g.N(this,this.A);this.B=new g.Ut(this.uE,1E3,this);g.N(this,this.B);this.J=new r5(this.TV,0,this);g.N(this,this.J);this.C={};this.K=new g.Ut(this.UE,1E3,this);g.N(this,this.K);this.I=new g.Qk(this.qO,1E3,this);g.N(this,this.I);this.M=g.y;this.xE();this.yp();this.sm()},t7=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.T("progresssync",b,d)},MBa=function(a){t7(a,0);
a.A.stop();u7(a,new g.rP(64))},w7=function(a,b){if(v7(a)&&!a.D){var c=null;
b&&(c={style:a.l.Gi()},g.dc(c,b));a.g.hE(a.l.getVideoData(1).videoId,c);a.C=O6(a.g).l}},x7=function(a,b){var c=a.l.cg();
if(c){var d=c.ge();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Qj;f=wza(f);var n=O6(c);l=l||0;var q={videoId:k,currentIndex:l};K6(n,k,l);g.t(b)&&(I6(n,b),q.currentTime=b);g.t(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.xg(f));S6(c,"setPlaylist",q);e||Q6(c,n);u7(a,new g.rP(1))},NBa=function(a,b){if(b){var c=a.l.wc("captions","tracklist",{Wz:1});
c&&c.length?(a.l.Kd("captions","track",b),a.D=!1):(a.l.ek("captions"),a.D=!0)}else a.l.Kd("captions","track",{})},v7=function(a){return O6(a.g).videoId==a.l.getVideoData(1).videoId},u7=function(a,b){a.B.stop();
var c=a.H;if(!g.wP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.eV(a.l,d);a.H=b;OBa(a.F,c,b)}},y7=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",N:[{G:"div",L:"ytp-remote-display-status",N:[{G:"div",L:"ytp-remote-display-status-icon",N:[g.zoa()]},{G:"div",L:"ytp-remote-display-status-text",aa:"{{statustext}}"}]}]});this.o=new g.RV(this,250);g.N(this,this.o);this.A=a;this.O(a,"presentingplayerstatechange",this.B);PBa(this,g.bV(a))},PBa=function(a,b){if(3==a.A.Qa()){var c={RECEIVER_NAME:a.A.wc("remote","currentReceiver").name};
c=g.X(b,128)?g.WZ("Error on $RECEIVER_NAME",c):b.kb()||g.X(b,4)?g.WZ("Playing on $RECEIVER_NAME",c):g.WZ("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},z7=function(a,b){g.OY.call(this,"Play on",0,a,b);
this.o=a;this.H={};this.O(a,"onMdxReceiversChange",this.J);this.O(a,"presentingplayerstatechange",this.J);this.J()},A7=function(a){g.yV.call(this,a);
this.o={key:c5(),name:"This computer"};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.rP(64);this.H=0;if(!g.MM(g.Y(this.g))){a=this.g;var b=g.zH(a);b&&(b=b.To())&&(b=new z7(a,b),g.N(this,b));b=new y7(a);g.N(this,b);g.tV(a,b.element,4)}},OBa=function(a,b,c){a.D=c;
a.g.T("presentingplayerstatechange",new g.BP(c,b))},B7=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)n7();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.cg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Xb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Qj,index:Math.max(a.g.XA(),0),currentTime:0==f?void 0:f};(d=wza(d))&&(c.locationInfo=d);d=c}else d=null;f7("Connecting to: "+g.xg(b));"cast-selector-receiver"==b.key?(h7(d||null),C6()?z6().setLaunchParams(d||null):
x6("setLaunchParams called before ready.")):!d&&q7()&&e7()==b.key?g.UF("yt-remote-connection-change",!0):(n7(),h7(d||null),d=d7().ie(),(d=e5(d,b.key))&&o7(d,1))}},dAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},B5={"'":"\\'"},QBa={},Cza={GX:"atp",d2:"ska",t1:"que",F0:"mus",Z1:"sus",OZ:"dsp"};
Y4.prototype.Mn=function(){var a=new Y4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var k5,g5="",o5=l5("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Wza=l5("loadCastFramework")||l5("loadCastApplicationFramework"),fBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(r5,g.M);g.h=r5.prototype;g.h.sJ=function(a){this.A=arguments;this.g=!1;this.Ba?this.o=(0,g.F)()+this.pd:this.Ba=g.rg(this.B,this.pd)};
g.h.stop=function(){this.Ba&&(g.sg(this.Ba),this.Ba=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();r5.ca.V.call(this)};
g.h.tJ=function(){this.o?(this.Ba=g.rg(this.B,this.o-(0,g.F)()),this.o=null):(this.Ba=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};s5.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
s5.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=t5.prototype;g.h.li=null;g.h.Bf=!1;g.h.Lk=null;g.h.Yv=null;g.h.uk=null;g.h.Hj=null;g.h.jh=null;g.h.Ih=null;g.h.Ni=null;g.h.Qc=null;g.h.Nm=0;g.h.Cf=null;g.h.wq=null;g.h.kh=null;g.h.Al=-1;g.h.OD=!0;g.h.Vh=!1;g.h.ys=0;g.h.Jp=null;var bAa={},w5={};g.h=t5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.NU=function(a){a=a.target;var b=this.Jp;b&&3==g.ex(a)?b.Fj():this.dF(a)};
g.h.dF=function(a){try{if(a==this.Qc)a:{var b=g.ex(this.Qc),c=this.Qc.l,d=this.Qc.getStatus();if(g.xd&&!g.qc(10)||g.zd&&!g.pc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.cf&&!g.ix(this.Qc))break a;this.Vh||4!=b||7==c||(8==c||0>=d?this.g.vf(3):this.g.vf(2));D5(this);var e=this.Qc.getStatus();this.Al=e;var f=g.ix(this.Qc);(this.Bf=200==e)?(4==b&&z5(this),this.B?(cAa(this,b,f),g.cf&&this.Bf&&3==b&&(this.W.U(this.l,"tick",this.JU),this.l.start())):y5(this,f),this.Bf&&!this.Vh&&(4==b?this.g.wp(this):
(this.Bf=!1,v5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.kh=3,x5(13)):(this.kh=0,x5(14)),z5(this),A5(this))}}catch(k){this.Qc&&g.ix(this.Qc)}finally{}};
g.h.JU=function(){var a=g.ex(this.Qc),b=g.ix(this.Qc);this.Nm<b.length&&(D5(this),cAa(this,a,b),this.Bf&&4!=a&&v5(this))};
g.h.UT=function(a){C5((0,g.z)(this.TT,this,a),0)};
g.h.TT=function(a){this.Vh||(D5(this),y5(this,a),v5(this))};
g.h.aD=function(a){C5((0,g.z)(this.ST,this,a),0)};
g.h.ST=function(a){this.Vh||(z5(this),this.Bf=a,this.g.wp(this),this.g.vf(4))};
g.h.cancel=function(){this.Vh=!0;z5(this)};
g.h.mU=function(){this.Lk=null;var a=(0,g.F)();0<=a-this.Yv?(2!=this.Hj&&this.g.vf(3),z5(this),this.kh=2,x5(18),A5(this)):fAa(this,this.Yv-a)};g.h=iAa.prototype;g.h.ws=null;g.h.re=null;g.h.Kp=!1;g.h.lz=null;g.h.Zn=null;g.h.Et=null;g.h.xs=null;g.h.Me=null;g.h.Bg=-1;g.h.zl=null;g.h.Uk=null;g.h.connect=function(a){this.xs=a;a=F5(this.g,null,this.xs);x5(3);this.lz=(0,g.F)();var b=this.g.F;null!=b?(this.zl=b[0],(this.Uk=b[1])?(this.Me=1,jAa(this)):(this.Me=2,H5(this))):(X4(a,"MODE","init"),this.re=new t5(this,void 0,void 0,void 0),this.re.li=this.ws,u5(this.re,a,!1,null,!0),this.Me=0)};
g.h.EI=function(a){if(a)this.Me=2,H5(this);else{x5(4);var b=this.g;b.Pf=b.ah.Bg;O5(b,9)}a&&this.vf(2)};
g.h.Lr=function(a){return this.g.Lr(a)};
g.h.abort=function(){this.re&&(this.re.cancel(),this.re=null);this.Bg=-1};
g.h.kz=function(){return!1};
g.h.TC=function(a,b){this.Bg=a.Al;if(0==this.Me)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Pf=this.Bg;O5(c,2);return}this.zl=c[0];this.Uk=c[1]}else c=this.g,c.Pf=this.Bg,O5(c,2);else if(2==this.Me)if(this.Kp)x5(7),this.Et=(0,g.F)();else if("11111"==b){if(x5(6),this.Kp=!0,this.Zn=(0,g.F)(),c=this.Zn-this.lz,!g.xd||g.qc(10)||500>c)this.Bg=200,this.re.cancel(),x5(12),G5(this.g,this,!0)}else x5(8),this.Zn=this.Et=(0,g.F)(),this.Kp=!1};
g.h.wp=function(){this.Bg=this.re.Al;if(this.re.Bf)0==this.Me?this.Uk?(this.Me=1,jAa(this)):(this.Me=2,H5(this)):2==this.Me&&((!g.xd||g.qc(10)?!this.Kp:200>this.Et-this.Zn)?(x5(11),G5(this.g,this,!1)):(x5(12),G5(this.g,this,!0)));else{0==this.Me?x5(9):2==this.Me&&x5(10);var a=this.g;a.Pf=this.Bg;O5(a,2)}};
g.h.Em=function(){return this.g.Em()};
g.h.isActive=function(){return this.g.isActive()};
g.h.vf=function(a){this.g.vf(a)};g.h=I5.prototype;g.h.kl=null;g.h.Vd=null;g.h.tc=null;g.h.us=null;g.h.eo=null;g.h.Bx=null;g.h.so=null;g.h.jm=0;g.h.JP=0;g.h.od=null;g.h.eh=null;g.h.qg=null;g.h.Zh=null;g.h.ah=null;g.h.uq=null;g.h.Vj=-1;g.h.lA=-1;g.h.Pf=-1;g.h.tj=0;g.h.hj=0;g.h.Xh=8;var P5=new g.Cf;g.A(lAa,g.af);g.A(mAa,g.af);g.A(nAa,g.af);g.h=I5.prototype;g.h.connect=function(a,b,c,d,e){x5(0);this.us=b;this.kl=c||{};d&&g.t(e)&&(this.kl.OSID=d,this.kl.OAID=e);this.C?(C5((0,g.z)(this.Wx,this,a),100),rAa(this)):this.Wx(a)};
g.h.Wx=function(a){this.ah=new iAa(this);this.ah.ws=null;this.ah.l=this.B;this.ah.connect(a)};
g.h.kz=function(){return 0==this.g};
g.h.YC=function(a){this.eh=null;uAa(this,a)};
g.h.XC=function(){this.qg=null;this.tc=new t5(this,this.o,"rpc",this.D);this.tc.li=null;this.tc.ys=0;var a=this.Bx.clone();g.zm(a,"RID","rpc");g.zm(a,"SID",this.o);g.zm(a,"CI",this.uq?"0":"1");g.zm(a,"AID",this.Vj);J5(this,a);if(!g.xd||g.qc(10))g.zm(a,"TYPE","xmlhttp"),u5(this.tc,a,!0,this.so,!1);else{g.zm(a,"TYPE","html");var b=this.tc,c=!!this.so;b.Hj=3;b.jh=W4(a.clone());eAa(b,c)}};
g.h.TC=function(a,b){if(0!=this.g&&(this.tc==a||this.Vd==a))if(this.Pf=a.Al,this.Vd==a&&3==this.g)if(7<this.Xh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.qg){if(this.tc)if(this.tc.uk+3E3<this.Vd.uk)L5(this),this.tc.cancel(),this.tc=null;else break a;N5(this);x5(19)}}else this.lA=c[1],0<this.lA-this.Vj&&37500>c[2]&&this.uq&&0==this.hj&&!this.Zh&&(this.Zh=C5((0,g.z)(this.mQ,this),6E3));else O5(this,11)}else b!=QBa.JY.g&&O5(this,11);else if(this.tc==a&&
L5(this),!g.C(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Vj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.so=e[2],e=e[3],null!=e?this.Xh=e:this.Xh=6,this.g=3,this.od&&this.od.Nx(),this.Bx=F5(this,this.Em()?this.so:null,this.us),vAa(this)):"stop"==e[0]&&O5(this,7):3==this.g&&("stop"==e[0]?O5(this,7):"noop"!=e[0]&&this.od&&this.od.Mx(e),this.hj=0)}}};
g.h.mQ=function(){null!=this.Zh&&(this.Zh=null,this.tc.cancel(),this.tc=null,N5(this),x5(20))};
g.h.wp=function(a){if(this.tc==a){L5(this);this.tc=null;var b=2}else if(this.Vd==a)this.Vd=null,b=1;else return;this.Pf=a.Al;if(0!=this.g)if(a.Bf)1==b?(b=(0,g.F)()-a.uk,P5.dispatchEvent(new mAa(P5,a.Ni?a.Ni.length:0,b,this.tj)),K5(this),this.A.length=0):vAa(this);else{var c=a.kh,d;if(!(d=3==c||7==c||0==c&&0<this.Pf)){if(d=1==b)this.Vd||this.eh||1==this.g||2<=this.tj?d=!1:(this.eh=C5((0,g.z)(this.YC,this,a),wAa(this,this.tj)),this.tj++,d=!0);d=!(d||2==b&&N5(this))}if(d)switch(c){case 1:O5(this,5);
break;case 4:O5(this,10);break;case 3:O5(this,6);break;case 7:O5(this,12);break;default:O5(this,2)}}};
g.h.bJ=function(a){if(!g.Pa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.FV=function(a){a?x5(2):(x5(1),xAa(this,8))};
g.h.Lr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Zw;a.F=!1;return a};
g.h.isActive=function(){return!!this.od&&this.od.isActive(this)};
g.h.vf=function(a){P5.dispatchEvent(new nAa(P5,a))};
g.h.Em=function(){return!(!g.xd||g.qc(10))};
g.h=yAa.prototype;g.h.Nx=function(){};
g.h.Mx=function(){};
g.h.Lx=function(){};
g.h.yr=function(){};
g.h.Ry=function(){return{}};
g.h.isActive=function(){return!0};g.A(Q5,g.M);g.h=Q5.prototype;g.h.KT=function(){this.pd=Math.min(3E5,2*this.pd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.pd+15E3*Math.random();g.Vt(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.pd=5E3};g.A(R5,yAa);g.h=R5.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Od=function(a){return this.o.Od(a)};
g.h.T=function(a,b){return this.o.T.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Ze(this.o),BAa(this),g.Ze(this.l),this.l=null)};
g.h.ka=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new I5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.g;e&&(e.od=null);d.od=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Vj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):S5(this)&&sAa(this.g,c)};
g.h.Nx=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)sAa(this.g,a[b])}this.T("handlerOpened")};
g.h.Lx=function(a){var b=2==a&&401==this.g.Pf;4==a||b||this.l.start();this.T("handlerError",a)};
g.h.yr=function(a){if(!this.l.isActive())this.T("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Ry=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.dc(a,this.B);return a};
g.h.Mx=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),qAa(this.g)):this.T("handlerMessage",new zAa(a[0],a[1]))};
g.h.lW=function(){this.l.isActive();var a=this.g,b=0;a.tc&&b++;a.Vd&&b++;0!=b||this.connect(this.B,this.A)};T5.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
T5.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
T5.prototype.B=function(a){a(Error("request timed out"))};var JAa=(0,g.F)(),W5=null,Z5=Array(50),Y5=-1,$5=!1;g.A(a6,g.EF);a6.prototype.ie=function(){return this.g};
a6.prototype.contains=function(a){return!!d5(this.g,a)};
a6.prototype.get=function(a){return a?e5(this.g,a):null};
a6.prototype.info=function(a){X5(this.D,a)};g.A(b6,g.EF);var RBa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=b6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ba)&&this.iF()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ba)||(g.VD(this.Ba),this.Ba=window.NaN)};
g.h.V=function(){this.stop();b6.ca.V.call(this)};
g.h.iF=function(){this.Ba=window.NaN;this.g=g.jE(U5(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.nW,this),onError:(0,g.z)(this.mW,this),wd:(0,g.z)(this.oW,this)})};
g.h.nW=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.T("pairingComplete",new Z4(c))};
g.h.mW=function(a){this.g=null;a.status&&404==a.status?this.l>=RBa.length?this.T("pairingFailed",Error("DIAL polling timed out")):(a=RBa[this.l],this.Ba=g.TD((0,g.z)(this.iF,this),a),this.l++):this.T("pairingFailed",Error("Server error "+a.status))};
g.h.oW=function(){this.g=null;this.T("pairingFailed",Error("Server not responding"))};g.A(d6,a6);g.h=d6.prototype;g.h.start=function(){c6(this)&&this.T("screenChange");!g.LG("yt-remote-lounge-token-expiration")&&NAa(this);g.VD(this.l);this.l=g.TD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){c6(this);KAa(this,a);e6(this,!1);this.T("screenChange");b(a);a.token||NAa(this)};
g.h.remove=function(a,b){var c=c6(this);MAa(this,a)&&(e6(this,!1),c=!0);b(a);c&&this.T("screenChange")};
g.h.oq=function(a,b,c,d){var e=c6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,e6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.T("screenChange")};
g.h.V=function(){g.VD(this.l);d6.ca.V.call(this)};
g.h.GJ=function(a){c6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}e6(this,!b);b&&X5(this.D,"Missed "+b+" lounge tokens.")};
g.h.FJ=function(a){X5(this.D,"Requesting lounge tokens failed: "+a)};g.A(g6,g.EF);g.h=g6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.LG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?i6(this):(this.A=(0,g.F)()+3E5,g.KG("yt-remote-fast-check-period",this.A),this.lv())};
g.h.isEmpty=function(){return g.Wb(this.g)};
g.h.update=function(){f6("Updating availability on schedule.");var a=this.C(),b=g.Kb(this.g,function(b,d){return b&&!!e5(a,d)},this);
h6(this,b)};
g.h.V=function(){g.VD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);g6.ca.V.call(this)};
g.h.lv=function(){g.VD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=QAa(this);if(g.Nb(a)){var b=U5(this.B,"/pairing/get_screen_availability");this.l=V5(this.B,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.rT,this,a),(0,g.z)(this.qT,this))}else h6(this,{}),i6(this)};
g.h.rT=function(a,b){this.l=null;var c=g.Qb(QAa(this));if(g.ib(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;h6(this,d);i6(this)}else this.fc("Changing Screen set during request."),this.lv()};
g.h.qT=function(a){this.fc("Screen availability failed: "+a);this.l=null;i6(this)};
g.h.fc=function(a){X5("OnlineScreenService",a)};g.A(j6,a6);g.h=j6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.T("screenChange"),this.l.isEmpty()||this.T("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.oq=function(a,b,c,d){this.o.contains(a)?this.o.oq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,X5(this.D,a),d(Error(a)))};
g.h.ie=function(a){return a?this.g:g.Wa(this.g,(0,g.Kd)(this.A,function(a){return!this.contains(a)},this))};
g.h.jF=function(){return(0,g.Kd)(this.ie(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.kF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new b6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Ze(f);d(k6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ze(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.qW=function(a,b,c,d){g.jE(U5(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new Z4(d.screen||{});if(!e.name||UAa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);UAa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(k6(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ze(this.o);g.Ze(this.l);j6.ca.V.call(this)};
g.h.VJ=function(){VAa(this);this.T("screenChange");this.l.update()};
j6.prototype.dispose=j6.prototype.dispose;g.A(m6,g.EF);g.h=m6.prototype;g.h.xp=function(a){this.o=a;this.T("sessionScreen",this.o)};
g.h.pe=function(a){this.ka()||(a&&n6(this,""+a),this.o=null,this.T("sessionScreen",null))};
g.h.info=function(a){X5(this.K,a)};
g.h.mF=function(){return null};
g.h.vv=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){n6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.vv("");m6.ca.V.call(this)};g.A(o6,m6);g.h=o6.prototype;g.h.uv=function(a){if(this.g){if(this.g==a)return;n6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);XAa(this)};
g.h.Xj=function(a){this.info("launchWithParams no-op for Cast: "+g.xg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.pe()},this),(0,g.z)(function(){this.pe(Error("Failed to stop receiver app."))},this)):this.pe(Error("Stopping cast device witout session."))};
g.h.vv=g.y;g.h.V=function(){this.info("disposeInternal");g.VD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;o6.ca.V.call(this)};
g.h.yU=function(a,b){if(!this.ka())if(b){var c=g.Tw(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.xg(c));switch(d){case "mdxSessionStatus":WAa(this,c.screenId);break;default:n6(this,"Unknown youtube message: "+d)}}else n6(this,"Unable to parse message.")}else n6(this,"No data in message.")};
g.h.bz=function(a,b,c,d){TAa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(n6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.TD((0,g.z)(this.bz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.mF=function(){return this.g};
g.h.rW=function(a){this.ka()||a||(n6(this,"Cast session died."),this.pe())};g.A(p6,m6);g.h=p6.prototype;g.h.uv=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.Xj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.VD(this.C);this.A?this.A.stop((0,g.z)(this.pe,this,null),(0,g.z)(this.pe,this,"Failed to stop DIAL device.")):this.pe()};
g.h.V=function(){this.g();this.g=g.y;g.VD(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;p6.ca.V.call(this)};
g.h.uW=function(a){this.ka()||a||(n6(this,"DIAL session died."),this.g(),this.g=g.y,this.pe())};
g.h.it=function(a){this.I=c5();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,ZAa(this));a(b);YAa(this)}else this.D=(0,g.z)(function(){g.VD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,ZAa(this));a(b);YAa(this)},this),this.C=g.TD((0,g.z)(function(){this.D()},this),100)};
g.h.jL=function(a,b,c){TAa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.xp(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.it(b,c)},this),(0,g.z)(function(a){n6(this,"Failed to get DIAL screen: "+a);
this.it(b,c)},this))};g.A(q6,m6);q6.prototype.stop=function(){this.pe()};
q6.prototype.uv=g.y;q6.prototype.Xj=function(){g.VD(this.g);this.g=window.NaN;var a=e5(this.H.ie(),this.l.label);a?this.xp(a):this.pe(Error("No such screen"))};
q6.prototype.V=function(){g.VD(this.g);this.g=window.NaN;q6.ca.V.call(this)};g.A(r6,g.EF);g.h=r6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.UC,this),(0,g.z)(this.bT,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.WQ,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.A),GAa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.lF,this)),this.o=aBa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.xg(a))},this)),this.T("yt-remote-cast2-availability-change",t6(this)),b(!0))},this),(0,g.z)(function(a){this.fc("Failed to initialize API: "+g.xg(a));
b(!1)},this))};
g.h.oV=function(a,b){s6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)s6("Unsetting old screen status: "+this.g.l.friendlyName),u6(this,null)}if(a&&b){if(!this.g){c=e5(this.l.ie(),a);if(!c){s6("setConnectedScreenStatus: Unknown screen.");return}var d=$Aa(this,c);d||(s6("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.xg(a))},this)));
s6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);u6(this,new q6(this.l,d),!0)}this.g.vv(b)}else s6("setConnectedScreenStatus: no screen.")};
g.h.pV=function(a){this.ka()?this.fc("Setting connection data on disposed cast v2"):this.g?this.g.Xj(a):this.fc("Setting connection data without a session")};
g.h.tW=function(){this.ka()?this.fc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),u6(this,null)):s6("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.UC,this),(0,g.z)(this.wT,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.lF,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],DAa);g.Ze(this.g);r6.ca.V.call(this)};
g.h.fc=function(a){X5("Controller",a)};
g.h.VC=function(a,b){this.g==a&&(b||u6(this,null),this.T("yt-remote-cast2-session-change",b))};
g.h.XS=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),s6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)s6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{s6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.T("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:u6(this,
new q6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:u6(this,new p6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:u6(this,new o6(this.l,a));break;default:this.fc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.fc("Stopping receiver w/o session: "+a.friendlyName)}else this.fc("onReceiverAction_ called without receiver.")};
g.h.WQ=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.fc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.fc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return s6("Reselecting dial screen."),
this.T("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.fc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);u6(this,new p6(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.jL,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.it,b))};
g.h.UC=function(a){if(!this.ka()){s6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)s6("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),u6(this,new o6(this.l,b),!0);else{this.fc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=e5(this.l.ie(),c.label);
d&&$4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(s6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ze(this.g),this.g=new o6(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.VC,this,this.g)),this.g.Xj(null));this.g.uv(a)}}};
g.h.sW=function(){return this.g?this.g.mF():null};
g.h.wT=function(a){this.ka()||(this.fc("Failed to estabilish a session: "+g.xg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&u6(this,null))};
g.h.bT=function(a){s6("Receiver availability updated: "+a);if(!this.ka()){var b=t6(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;t6(this)!=b&&this.T("yt-remote-cast2-availability-change",t6(this))}};
g.h.lF=function(){this.ka()||(this.o=aBa(this),s6("Updating custom receivers: "+g.xg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.fc("Failed to set custom receivers.")},this)),this.T("yt-remote-cast2-availability-change",t6(this)))};
r6.prototype.setLaunchParams=r6.prototype.pV;r6.prototype.setConnectedScreenStatus=r6.prototype.oV;r6.prototype.stopSession=r6.prototype.tW;r6.prototype.getCastSession=r6.prototype.sW;r6.prototype.requestSession=r6.prototype.requestSession;r6.prototype.init=r6.prototype.init;r6.prototype.dispose=r6.prototype.dispose;var A6=[];g.h=F6.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";G6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Sf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+H6(this):this.H};
g.h.clone=function(){return new F6(L6(this))};g.A(N6,g.EF);g.h=N6.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,T6(this,"play")):S6(this,"play"),R6(this,1,J6(O6(this))),this.T("remotePlayerChange")):P6(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,T6(this,"pause")):S6(this,"pause"),R6(this,2,J6(O6(this))),this.T("remotePlayerChange")):P6(this,this.pause)};
g.h.hF=function(a){if(1==this.g){if(this.l){var b=O6(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,T6(this,"seekTo",{newTime:a}))}else S6(this,"seekTo",{newTime:a});R6(this,3,a);this.T("remotePlayerChange")}else P6(this,g.Fa(this.hF,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,T6(this,"stopVideo")):S6(this,"stopVideo");var a=O6(this);a.index=-1;a.videoId="";G6(a);Q6(this,a);this.T("remotePlayerChange")}else P6(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=O6(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){X5("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.fc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){X5("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.fc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);S6(this,"setVolume",e)}c.muted=b;c.volume=a;Q6(this,c)}else P6(this,g.Fa(this.setVolume,a,b))};
g.h.hE=function(a,b){if(1==this.g){var c=O6(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xg(b.style),g.dc(d,c.l));S6(this,"setSubtitlesTrack",d);Q6(this,c)}else P6(this,g.Fa(this.hE,a,b))};
g.h.ew=function(a,b){if(1==this.g){S6(this,"setAudioTrack",{videoId:a,audioTrackId:b.Fb.id});var c=O6(this);c.audioTrackId=b.Fb.id;Q6(this,c)}else P6(this,g.Fa(this.ew,a,b))};
g.h.gF=function(a,b){if(1==this.g){if(a&&b){var c=O6(this);K6(c,a,b);Q6(this,c)}S6(this,"previous")}else P6(this,g.Fa(this.gF,a,b))};
g.h.fF=function(a,b){if(1==this.g){if(a&&b){var c=O6(this);K6(c,a,b);Q6(this,c)}S6(this,"next")}else P6(this,g.Fa(this.fF,a,b))};
g.h.ty=function(){1==this.g?S6(this,"dismissAutoplay"):P6(this,this.ty)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.T("proxyStateChange",a,this.g)}N6.ca.dispose.call(this)};
g.h.V=function(){nBa(this);this.A=null;this.B.clear();M6(this,null);N6.ca.V.call(this)};
g.h.gw=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.T("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.mC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.RS=function(a,b){this.T(a,b)};
g.h.tQ=function(a){if(!a)this.pm(null),M6(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=O6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)X5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,Q6(this,b)}};
g.h.pm=function(a){X5("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),oBa(this),this.T("remotePlayerChange")};
g.h.sQ=function(a){a?(oBa(this),this.T("remotePlayerChange")):this.pm(null)};
g.h.FQ=function(){var a=kBa();a&&M6(this,a)};
g.h.fc=function(a){X5("CP",a)};g.A(U6,g.EF);g.h=U6.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;I6(this.Za,m);this.A="UNSUPPORTED";V6("Connecting with setPlaylist and params: "+g.xg(l));this.g.connect({method:"setPlaylist",
params:g.xg(l)},a,Kza())}else V6("Connecting without params"),this.g.connect({},a,Kza());qBa(this)};
g.h.dispose=function(){this.ka()||(this.T("beforeDispose"),W6(this,3));U6.ca.dispose.call(this)};
g.h.V=function(){X6(this);Z6(this);Y6(this);g.VD(this.H);this.H=window.NaN;g.VD(this.I);this.I=window.NaN;this.o=null;g.oF(this.R);this.R.length=0;this.g.dispose();U6.ca.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.xJ=function(){this.C(2)};
g.h.xQ=function(){V6("Channel opened");this.M&&(this.M=!1,Y6(this),this.K=g.TD((0,g.z)(function(){V6("Timing out waiting for a screen.");this.C(1)},this),15E3));
Oza(AAa(this.g),this.Y)};
g.h.uQ=function(){V6("Channel closed");(0,window.isNaN)(this.B)?j5(!0):j5();this.dispose()};
g.h.vQ=function(a){j5();(0,window.isNaN)(this.F())?(V6("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,V6("Channel error: "+a+" with reconnection in "+this.F()+" ms"),W6(this,2))};
g.h.wQ=function(a){a.params?V6("Received: action="+a.action+", params="+g.xg(a.params)):V6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Tw(a.params.devices);this.l=(0,g.G)(a,function(a){return new Y4(a)});
a=!!g.La(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
tBa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
tBa(this,!1);break;case "remoteConnected":var b=new Y4(g.Tw(a.params.device));g.La(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new Y4(g.Tw(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":vBa(this,a);break;case "nowPlaying":xBa(this,a);break;case "onStateChange":wBa(this,a);break;case "onAdStateChange":yBa(this,a);break;case "onVolumeChanged":zBa(this,a);break;case "onSubtitlesTrackChanged":uBa(this,a);break;case "nowAutoplaying":ABa(this,a);break;case "autoplayDismissed":this.T("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.T("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.T("autoplayModeChange",this.A);"DISABLED"==this.A&&this.T("autoplayDismissed");break;case "onHasPreviousNextChanged":BBa(this,a);break;case "requestAssistedSignIn":this.T("assistedSignInRequested",a.params.authCode);break;default:V6("Unrecognized action: "+a.action)}};
g.h.YU=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&$6(this,"getNowPlaying")}};
U6.prototype.subscribe=U6.prototype.subscribe;U6.prototype.unsubscribeByKey=U6.prototype.Od;U6.prototype.ga=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.F())?S5(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
U6.prototype.getProxyState=U6.prototype.ga;U6.prototype.C=function(a){V6("Disconnecting with "+a);X6(this);this.T("beforeDisconnect",a);1==a&&j5();BAa(this.g,a);this.dispose()};
U6.prototype.disconnect=U6.prototype.C;U6.prototype.fa=function(){var a=this.Za;this.o&&(a=this.Za.clone(),K6(a,this.o,a.index));return L6(a)};
U6.prototype.getPlayerContextData=U6.prototype.fa;
U6.prototype.na=function(a){var b=new F6(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.VD(this.H),this.H=g.TD((0,g.z)(this.YU,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&J6(this.Za)==J6(b)&&g.xg(this.Za.l)==g.xg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.T(a)},this)};
U6.prototype.setPlayerContextData=U6.prototype.na;U6.prototype.X=function(){var a=this.g.C.id,b=g.La(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
U6.prototype.getOtherConnectedRemoteId=U6.prototype.X;U6.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
U6.prototype.getReconnectTimeout=U6.prototype.F;U6.prototype.Z=function(){return this.A||"UNSUPPORTED"};
U6.prototype.getAutoplayMode=U6.prototype.Z;U6.prototype.ba=function(){return this.D||""};
U6.prototype.getAutoplayVideoId=U6.prototype.ba;U6.prototype.sa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Wt(a.g);a.start()}};
U6.prototype.reconnect=U6.prototype.sa;U6.prototype.ia=function(a,b){$6(this,a,b);sBa(this)};
U6.prototype.sendMessage=U6.prototype.ia;g.A(a7,a6);g.h=a7.prototype;g.h.ie=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.oq=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.dd.$_ubk(this.l[a]);this.l.length=0;this.dd=null;a7.ca.V.call(this)};
g.h.pW=function(){this.T("screenChange")};
g.h.sS=function(){this.T("onlineScreenChange")};
j6.prototype.$_st=j6.prototype.start;j6.prototype.$_gspc=j6.prototype.qW;j6.prototype.$_gsppc=j6.prototype.kF;j6.prototype.$_c=j6.prototype.contains;j6.prototype.$_g=j6.prototype.get;j6.prototype.$_a=j6.prototype.add;j6.prototype.$_un=j6.prototype.oq;j6.prototype.$_r=j6.prototype.remove;j6.prototype.$_gs=j6.prototype.ie;j6.prototype.$_gos=j6.prototype.jF;j6.prototype.$_s=j6.prototype.subscribe;j6.prototype.$_ubk=j6.prototype.Od;var b7=null,c7=null,r7=null,g7=[];g.p(s7,g.M);g.h=s7.prototype;
g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.J.stop();this.M();this.g.unsubscribe("proxyStateChange",this.SC,this);this.g.unsubscribe("remotePlayerChange",this.sm,this);this.g.unsubscribe("remoteQueueChange",this.yp,this);this.g.unsubscribe("autoplayUpNext",this.qC,this);this.g.unsubscribe("previousNextChange",this.PC,this);this.g.unsubscribe("nowAutoplaying",this.HC,this);this.g.unsubscribe("autoplayDismissed",this.pC,this);this.g=this.F=null};
g.h.rB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(v7(this)){if(!O6(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":O6(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Fj(c[0],c[1]);break;case "control_subtitles_set_track":w7(this,c[0]);break;case "control_set_audio_track":c=c[0],v7(this)&&this.g.ew(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();x7(this,0==c?void 0:c);break;case "control_seek":x7(this,c[0]);break;case "control_subtitles_set_track":w7(this,c[0]);break;case "control_set_audio_track":c=c[0],v7(this)&&this.g.ew(this.l.getVideoData(1).videoId,c)}};
g.h.rQ=function(a){this.J.sJ(a)};
g.h.TV=function(a){this.rB("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.xE=function(){var a=this.l.wc("captions","track");g.Wb(a)||w7(this,a)};
g.h.FC=function(a){if(v7(this)){this.g.unsubscribe("remotePlayerChange",this.sm,this);var b=Math.round(a.volume);a=!!a.muted;var c=O6(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.sm,this)}};
g.h.MR=function(){g.Wb(this.C)||NBa(this,this.C);this.D=!1};
g.h.SC=function(a,b){this.B.stop();2==b&&this.uE()};
g.h.sm=function(){if(v7(this)){this.A.stop();var a=O6(this.g);switch(a.g){case 1081:case 1:u7(this,new g.rP(8));this.tE();break;case 1085:case 3:u7(this,new g.rP(9));break;case 1083:case 0:u7(this,new g.rP(2));this.I.stop();t7(this,this.l.getVideoData().lengthSeconds);break;case 1084:u7(this,new g.rP(4));break;case 2:u7(this,new g.rP(4));t7(this,J6(a));break;case -1:u7(this,new g.rP(64));break;case -1E3:u7(this,new g.rP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
O6(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,NBa(this,a));a=O6(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.K.isActive()||this.UE()}else MBa(this)};
g.h.PC=function(){this.l.T("mdxpreviousnextchange")};
g.h.yp=function(){v7(this)||MBa(this)};
g.h.DI=function(){this.g.ty()};
g.h.qC=function(a){a&&(a=g.jE("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.ZT,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.ZT=function(a,b){var c=new g.jO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.T("mdxautoplayupnext",c)};
g.h.HC=function(a){(0,window.isNaN)(a)||this.l.T("mdxnowautoplaying",a)};
g.h.pC=function(){this.l.T("mdxautoplaycanceled")};
g.h.qO=function(a,b){-1==O6(this.g).g?x7(this,a):b&&this.g.hF(a)};
g.h.UE=function(){if(v7(this)){var a=O6(this.g);this.o.Da(this.R);a.muted?this.l.mute():this.l.dg();this.l.setVolume(a.volume);this.R=this.o.O(this.l,"onVolumeChange",this.FC)}};
g.h.tE=function(){this.A.stop();if(!this.g.ka()){var a=O6(this.g);a.kb()&&u7(this,new g.rP(8));t7(this,J6(a));this.A.start()}};
g.h.uE=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(y7,g.W);y7.prototype.B=function(a){PBa(this,a.state)};g.p(z7,g.OY);z7.prototype.J=function(){var a=this.o.wc("remote","receivers");a&&1<a.length&&!this.o.wc("remote","quickCast")?(this.H=g.kb(a,this.C,this),g.PY(this,(0,g.G)(a,this.C)),a=this.o.wc("remote","currentReceiver"),this.uf(this.C(a)),this.enable(!0)):this.enable(!1)};
z7.prototype.C=function(a){return a.key};
z7.prototype.tf=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
z7.prototype.td=function(a){g.OY.prototype.td.call(this,a);this.o.Kd("remote","currentReceiver",this.H[a]);this.B.Pb()};g.p(A7,g.yV);g.h=A7.prototype;g.h.create=function(){GBa(g.zM(g.Y(this.g)));this.C.push(g.QF("yt-remote-before-disconnect",this.nQ,this));this.C.push(g.QF("yt-remote-connection-change",this.cT,this));this.C.push(g.QF("yt-remote-receiver-availability-change",this.QC,this));this.C.push(g.QF("yt-remote-auto-connect",this.aT,this));this.C.push(g.QF("yt-remote-receiver-resumed",this.ZS,this));this.QC()};
g.h.load=function(){this.g.hu();g.yV.prototype.load.call(this);this.B=new s7(this,this.g,this.l);var a=(a=LBa())?a.currentTime:0;var b=q7()?new N6(l7(),void 0):null;0==a&&b&&(a=J6(O6(b)));0!=a&&(this.H=a||0,this.g.T("progresssync",a,void 0));OBa(this,this.D,this.D);g.BZ(this.g.app,6)};
g.h.unload=function(){this.g.T("mdxautoplaycanceled");this.A=this.o;g.$e(this.B,this.l);this.l=this.B=null;g.yV.prototype.unload.call(this);g.BZ(this.g.app,5)};
g.h.V=function(){g.RF(this.C);g.yV.prototype.V.call(this)};
g.h.fm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.rB.apply(this.B,[a].concat(g.pa(c)))};
g.h.oJ=function(){return this.loaded?this.B.suggestion:null};
g.h.Sf=function(){return this.l?O6(this.l).Sf:!1};
g.h.hasNext=function(){return this.l?O6(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.eO=function(){var a=O6(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+H6(a):a.A,isPeggedToLive:1>=(a.C?a.o+H6(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+H6(a):a.o,seekableStart:0<a.B?a.B+H6(a):a.B}};
g.h.fO=function(){this.l&&this.l.fF()};
g.h.gO=function(){this.l&&this.l.gF()};
g.h.nQ=function(a){1==a&&(this.I=this.l?O6(this.l):null)};
g.h.cT=function(){var a=q7()?new N6(l7(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ze(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.VA(a.videoId,J6(a)));this.g.T("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.QC=function(){this.F=[this.o].concat(IBa());var a=m7()||this.o;B7(this,a);this.g.va("onMdxReceiversChange")};
g.h.aT=function(){var a=m7();B7(this,a)};
g.h.ZS=function(){this.A=m7()};
g.h.dO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?D6():B7(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&D6(),!0):!1}};
g.h.hO=function(){S6(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Gc=function(){return!1};g.iY.remote=A7;})(_yt_player);
